export type CertCategory = 'QA Fundamentals' | 'Automation' | 'AI Testing' | 'AI/ML Engineering' | 'Cloud AI' | 'Security' | 'Agile & Process';

export type CertDifficulty = 'Beginner' | 'Intermediate' | 'Advanced' | 'Expert';

export interface StudyResource {
  type: 'Official Docs' | 'Book' | 'Course' | 'Practice Exam' | 'YouTube' | 'GitHub' | 'Website';
  title: string;
  url?: string;
  free: boolean;
  note?: string;
}

export interface ExamTopic {
  name: string;
  weight: string;
}

export interface Certification {
  id: string;
  name: string;
  shortName: string;
  issuer: string;
  issuerLogo: string;
  category: CertCategory;
  difficulty: CertDifficulty;
  duration: string;
  cost: string;
  validity: string;
  passMark: string;
  questions: string;
  format: string;
  languages: string[];
  description: string;
  whyGetIt: string;
  careerImpact: string;
  prerequisites: string[];
  examTopics: ExamTopic[];
  studyResources: StudyResource[];
  tips: string[];
  relatedCerts: string[];
  popular: boolean;
  newBadge?: boolean;
  countryRecognition: string[];
}

export const certifications: Certification[] = [

  // ── QA FUNDAMENTALS ──────────────────────────────────────────────────────

  {
    id: 'istqb-ctfl',
    name: 'ISTQB Certified Tester Foundation Level',
    shortName: 'ISTQB CTFL',
    issuer: 'ISTQB',
    issuerLogo: '🏛️',
    category: 'QA Fundamentals',
    difficulty: 'Beginner',
    duration: '4–6 weeks study',
    cost: '$150–$250 (varies by country)',
    validity: 'Lifetime (no renewal)',
    passMark: '65% (39/60 questions)',
    questions: '40 multiple choice, 60 min',
    format: 'Multiple choice, closed book',
    languages: ['English', 'German', 'French', 'Spanish', 'Japanese', 'Chinese', 'Arabic', 'Hindi', 'Turkish', 'Portuguese'],
    description: 'The world\'s most widely held software testing certification. Covers the fundamentals of testing theory, test design techniques, test management, and the software development lifecycle. Recognised by virtually every QA employer globally.',
    whyGetIt: 'Required or strongly preferred by TCS, Infosys, Wipro, Capgemini, Accenture, and most service companies. Provides common vocabulary and a structured understanding of testing principles. Acts as a gateway to all ISTQB advanced levels.',
    careerImpact: 'Salary uplift of 10–20% for juniors in India, UK, and Europe. Often required for client-site placements in service companies. Opens doors to ISTQB advanced certifications.',
    prerequisites: [],
    examTopics: [
      { name: 'Fundamentals of Testing', weight: '26%' },
      { name: 'Testing Throughout the SDLC', weight: '20%' },
      { name: 'Static Testing', weight: '14%' },
      { name: 'Test Analysis & Design (BVA, EP, Decision Tables)', weight: '22%' },
      { name: 'Managing the Test Activities', weight: '14%' },
      { name: 'Test Tools', weight: '4%' },
    ],
    studyResources: [
      { type: 'Official Docs', title: 'ISTQB CTFL Syllabus v4.0', free: true, note: 'Download from istqb.org — this IS the exam' },
      { type: 'Official Docs', title: 'ISTQB Glossary (online)', free: true, note: 'Know every term — questions are vocabulary heavy' },
      { type: 'Book', title: 'Foundations of Software Testing (Dorothy Graham)', free: false, note: 'The classic companion book to the syllabus' },
      { type: 'Practice Exam', title: 'ISTQB Official Sample Papers', free: true, note: 'Available on istqb.org — do all sample papers' },
      { type: 'Practice Exam', title: 'Guru99 ISTQB Mock Tests', free: true },
      { type: 'Course', title: 'ISTQB CTFL — Udemy (Oleg Skrypnyk)', free: false, note: 'Highest-rated paid course' },
      { type: 'YouTube', title: 'ISTQB Foundation Level Full Course — Software Testing Mentor', free: true },
      { type: 'Website', title: 'practicesoftwaretesting.com', free: true, note: 'Practice questions and explanations' },
    ],
    tips: [
      'Read the official syllabus v4.0 cover to cover — the exam is written directly from it',
      'Learn EVERY term in the ISTQB Glossary; many questions test definitions',
      'Do at least 200 practice questions before the exam',
      'Pay special attention to test design techniques (BVA, EP, Decision Tables) — 22% of marks',
      'Understand the difference between verification and validation, error/defect/failure',
      'Time is generous — 40 questions in 60 mins; review all answers before submitting',
    ],
    relatedCerts: ['istqb-ctal-tm', 'istqb-ctal-ta', 'istqb-ct-ai', 'istqb-ct-at'],
    popular: true,
    countryRecognition: ['India', 'UK', 'Germany', 'USA', 'UAE', 'Canada', 'Australia', 'Netherlands', 'Poland', 'Brazil'],
  },

  {
    id: 'istqb-ctal-tm',
    name: 'ISTQB Advanced Level Test Manager',
    shortName: 'ISTQB CTAL-TM',
    issuer: 'ISTQB',
    issuerLogo: '🏛️',
    category: 'QA Fundamentals',
    difficulty: 'Advanced',
    duration: '8–12 weeks study',
    cost: '$250–$400',
    validity: 'Lifetime',
    passMark: '65%',
    questions: '65 questions, 180 min',
    format: 'Multiple choice + complex multiple choice',
    languages: ['English', 'German', 'French', 'Spanish'],
    description: 'Advanced certification for experienced test managers. Covers test strategy, risk-based testing, defect management, test process improvement, and test tools. Targets QA Leads and Managers with 3+ years experience.',
    whyGetIt: 'Validates expertise in test management, strategy, and leadership. Required for senior QA roles at many enterprise clients. Differentiates experienced testers from junior/mid level.',
    careerImpact: 'Opens QA Lead and QA Manager roles. 20–35% salary premium over Foundation Level. Required for client delivery manager roles at consulting firms.',
    prerequisites: ['ISTQB CTFL (Foundation Level)'],
    examTopics: [
      { name: 'Testing Process', weight: '18%' },
      { name: 'Test Management in Context', weight: '16%' },
      { name: 'Risk-Based Testing', weight: '18%' },
      { name: 'Test Documentation', weight: '12%' },
      { name: 'Defect Management', weight: '12%' },
      { name: 'Test Process Improvement', weight: '12%' },
      { name: 'Test Tools & Automation', weight: '12%' },
    ],
    studyResources: [
      { type: 'Official Docs', title: 'ISTQB CTAL-TM Syllabus', free: true, note: 'Download from istqb.org' },
      { type: 'Book', title: 'Advanced Software Testing Vol. 3 — Rex Black', free: false },
      { type: 'Practice Exam', title: 'ISTQB Advanced Sample Papers', free: true },
      { type: 'Course', title: 'CTAL-TM Preparation — Udemy', free: false },
    ],
    tips: [
      'Must pass Foundation Level first',
      'Focus heavily on risk-based testing methodology — highest weighting',
      'Understand TMMi (Test Maturity Model) process improvement',
      'Study IEEE 829 test documentation formats',
      'Practice calculating defect removal efficiency and test metrics',
    ],
    relatedCerts: ['istqb-ctfl', 'istqb-ctal-ta', 'csqe'],
    popular: true,
    countryRecognition: ['UK', 'Germany', 'Netherlands', 'India', 'USA', 'UAE'],
  },

  {
    id: 'istqb-ctal-ta',
    name: 'ISTQB Advanced Level Test Analyst',
    shortName: 'ISTQB CTAL-TA',
    issuer: 'ISTQB',
    issuerLogo: '🏛️',
    category: 'QA Fundamentals',
    difficulty: 'Advanced',
    duration: '8–10 weeks study',
    cost: '$250–$400',
    validity: 'Lifetime',
    passMark: '65%',
    questions: '65 questions, 180 min',
    format: 'Multiple choice + complex multiple choice',
    languages: ['English', 'German', 'French'],
    description: 'Advanced certification for test analysts. Deep dive into test design techniques, black-box testing, experience-based testing, and testing for specific quality characteristics (usability, accessibility, performance).',
    whyGetIt: 'Best certification for hands-on testers who want to validate deep test design skills. Covers advanced test techniques beyond Foundation Level.',
    careerImpact: 'Senior QA Analyst roles. Strong credential for client-facing testing roles in finance, healthcare, and government sectors.',
    prerequisites: ['ISTQB CTFL (Foundation Level)'],
    examTopics: [
      { name: 'Test Management — the Analyst\'s tasks', weight: '8%' },
      { name: 'Test Analysis & Design Techniques', weight: '36%' },
      { name: 'Testing of Product Quality Characteristics', weight: '24%' },
      { name: 'Reviews', weight: '16%' },
      { name: 'Defect Management', weight: '16%' },
    ],
    studyResources: [
      { type: 'Official Docs', title: 'ISTQB CTAL-TA Syllabus', free: true },
      { type: 'Book', title: 'Advanced Software Testing Vol. 1 — Rex Black', free: false },
      { type: 'Practice Exam', title: 'ISTQB Advanced Sample Papers', free: true },
    ],
    tips: [
      'Master all 7 advanced test design techniques — this is 36% of the exam',
      'Understand state transition testing and cause-effect graphing thoroughly',
      'Study ISO/IEC 25010 quality characteristics — they form the basis of quality testing chapter',
    ],
    relatedCerts: ['istqb-ctfl', 'istqb-ctal-tm', 'istqb-ctal-tta'],
    popular: false,
    countryRecognition: ['UK', 'Germany', 'India', 'Netherlands'],
  },

  {
    id: 'istqb-ct-ai',
    name: 'ISTQB Certified Tester AI Testing',
    shortName: 'ISTQB CT-AI',
    issuer: 'ISTQB',
    issuerLogo: '🏛️',
    category: 'AI Testing',
    difficulty: 'Intermediate',
    duration: '6–8 weeks study',
    cost: '$200–$350',
    validity: 'Lifetime',
    passMark: '65%',
    questions: '40 multiple choice, 60 min',
    format: 'Multiple choice, closed book',
    languages: ['English', 'German'],
    description: 'Specialist certification covering testing AI/ML systems. Topics include ML model quality, data quality testing, AI-specific test techniques, explainability testing, and bias/fairness testing. One of the first mainstream AI testing certifications.',
    whyGetIt: 'First-mover advantage — very few testers hold this. Immediately differentiates you as an AI Quality Engineer. Demand for AI testing skills is growing 5x faster than traditional QA roles.',
    careerImpact: 'Directly qualifies for AI Quality Engineer roles. 30–50% salary premium over standard QA. Sought by fintech, healthtech, and any company deploying ML systems.',
    prerequisites: ['ISTQB CTFL recommended but not mandatory'],
    examTopics: [
      { name: 'Introduction to AI', weight: '10%' },
      { name: 'ML Model Quality', weight: '20%' },
      { name: 'Data Quality', weight: '18%' },
      { name: 'Testing ML-based Systems', weight: '28%' },
      { name: 'Test Environments for AI', weight: '12%' },
      { name: 'AI-based Test Tools', weight: '12%' },
    ],
    studyResources: [
      { type: 'Official Docs', title: 'ISTQB CT-AI Syllabus v1.0', free: true, note: 'Core study material — read multiple times' },
      { type: 'Course', title: 'Machine Learning for Testers — LinkedIn Learning', free: false },
      { type: 'Course', title: 'AI Testing — Test Automation University', free: true },
      { type: 'Book', title: 'Testing AI Systems — Mark Utting', free: false },
      { type: 'Website', title: 'responsible-ai.org resources', free: true },
      { type: 'YouTube', title: 'Marktesting AI — YouTube channel', free: true },
    ],
    tips: [
      'Study ML concepts before attempting — understand supervised/unsupervised learning, training/test split',
      'Understand the difference between testing OF AI (testing the model) vs testing WITH AI (using AI to test)',
      'Know the 8 data quality dimensions from the syllabus',
      'Understand bias types: selection bias, measurement bias, algorithmic bias',
      'Study metamorphic testing — a key technique unique to AI testing',
    ],
    relatedCerts: ['istqb-ctfl', 'google-ml-engineer', 'aws-ai-practitioner'],
    popular: true,
    newBadge: true,
    countryRecognition: ['UK', 'Germany', 'USA', 'Netherlands', 'India'],
  },

  {
    id: 'istqb-ct-at',
    name: 'ISTQB Certified Tester Agile Tester',
    shortName: 'ISTQB CT-ATE',
    issuer: 'ISTQB',
    issuerLogo: '🏛️',
    category: 'Agile & Process',
    difficulty: 'Intermediate',
    duration: '4–6 weeks study',
    cost: '$150–$250',
    validity: 'Lifetime',
    passMark: '65%',
    questions: '40 multiple choice, 60 min',
    format: 'Multiple choice, closed book',
    languages: ['English', 'German', 'Spanish'],
    description: 'Covers testing practices in Agile and Scrum environments, including continuous testing, exploratory testing, TDD/BDD, and testing in sprints. Extends Foundation Level with Agile-specific practices.',
    whyGetIt: 'Most teams run Agile. This certification validates you can work effectively in sprint-based delivery without heavyweight test processes.',
    careerImpact: 'Particularly valued in product companies and startups. Complements CTFL for professionals in Agile shops.',
    prerequisites: ['ISTQB CTFL (Foundation Level)'],
    examTopics: [
      { name: 'Agile Testing Background', weight: '15%' },
      { name: 'Fundamental Agile Testing Principles, Practices and Processes', weight: '35%' },
      { name: 'Agile Testing Methods, Techniques and Tools', weight: '50%' },
    ],
    studyResources: [
      { type: 'Official Docs', title: 'ISTQB CT-ATE Syllabus', free: true },
      { type: 'Book', title: 'More Agile Testing — Lisa Crispin & Janet Gregory', free: false, note: 'The definitive resource' },
      { type: 'Book', title: 'Agile Testing — Lisa Crispin & Janet Gregory', free: false },
      { type: 'Course', title: 'Agile Testing — Udemy', free: false },
    ],
    tips: [
      'Read "Agile Testing" by Crispin & Gregory — the authors contributed to the syllabus',
      'Understand the Agile Testing Quadrants model',
      'Know BDD (Gherkin/Cucumber) basics and how they fit into sprint testing',
      'Understand whole-team quality responsibility vs traditional QA gating',
    ],
    relatedCerts: ['istqb-ctfl', 'safe-agilist'],
    popular: false,
    countryRecognition: ['UK', 'Germany', 'India', 'USA', 'Canada'],
  },

  {
    id: 'csqe',
    name: 'Certified Software Quality Engineer',
    shortName: 'CSQE (ASQ)',
    issuer: 'ASQ (American Society for Quality)',
    issuerLogo: '🇺🇸',
    category: 'QA Fundamentals',
    difficulty: 'Advanced',
    duration: '3–6 months study',
    cost: '$398 (ASQ member) / $498 (non-member)',
    validity: '3 years (recertification required)',
    passMark: 'Scaled score 550/800',
    questions: '160 multiple choice, 4.5 hours',
    format: 'Multiple choice, open book (paper-based reference allowed)',
    languages: ['English'],
    description: 'Prestigious USA-centric certification covering software quality systems, software design and development, software testing and inspection, software maintenance, quality management, and professional practices.',
    whyGetIt: 'Gold standard quality certification in North America. Highly respected in aerospace, defence, medical device, and automotive industries. Open-book format rewards deep understanding over memorisation.',
    careerImpact: 'Essential for quality engineering roles in regulated industries (FDA, FAA, DoD). Strong credential for QA Managers and Directors in the US and Canada.',
    prerequisites: ['8 years experience in software quality OR relevant degree reduces this to 4–6 years'],
    examTopics: [
      { name: 'General Knowledge, Conduct & Ethics', weight: '5%' },
      { name: 'Software Quality Management', weight: '20%' },
      { name: 'Software Quality Metrics', weight: '8%' },
      { name: 'Software Design & Development', weight: '16%' },
      { name: 'Software Testing & Inspection', weight: '28%' },
      { name: 'Software Maintenance & Sustainment', weight: '7%' },
      { name: 'Software Quality Tools', weight: '16%' },
    ],
    studyResources: [
      { type: 'Official Docs', title: 'ASQ CSQE Body of Knowledge', free: true, note: 'Download from asq.org' },
      { type: 'Book', title: 'The Certified Software Quality Engineer Handbook — Linda Westfall', free: false, note: 'The primary study guide — worth every penny' },
      { type: 'Practice Exam', title: 'ASQ CSQE Sample Questions', free: true },
      { type: 'Course', title: 'ASQ CSQE Exam Prep — ASQ Learning Institute', free: false },
    ],
    tips: [
      'This is open book — build a well-tabbed reference guide from the BOK',
      'Study ISO 9001, IEEE standards, CMM/CMMI',
      'The exam is very long — practice time management with full mock exams',
      'Understand statistical quality control (SPC, control charts)',
    ],
    relatedCerts: ['istqb-ctal-tm', 'pmp'],
    popular: false,
    countryRecognition: ['USA', 'Canada', 'Germany'],
  },

  // ── AUTOMATION ───────────────────────────────────────────────────────────

  {
    id: 'istqb-ct-tae',
    name: 'ISTQB Certified Tester Test Automation Engineer',
    shortName: 'ISTQB CT-TAE',
    issuer: 'ISTQB',
    issuerLogo: '🏛️',
    category: 'Automation',
    difficulty: 'Intermediate',
    duration: '6–8 weeks study',
    cost: '$200–$350',
    validity: 'Lifetime',
    passMark: '65%',
    questions: '40 multiple choice, 60 min',
    format: 'Multiple choice, closed book',
    languages: ['English', 'German'],
    description: 'Covers test automation architecture, design patterns (Page Object Model, data-driven, keyword-driven), tool selection, CI/CD integration, automation metrics, and maintenance. Framework-agnostic but examples use common tools.',
    whyGetIt: 'Validates automation engineering skills with an internationally recognised credential. Differentiates SDETs from manual testers making the automation transition.',
    careerImpact: 'SDET and automation engineer roles. Strong differentiator in countries where automation skill is expected but not always formally validated.',
    prerequisites: ['ISTQB CTFL recommended'],
    examTopics: [
      { name: 'Introduction & Rationale for Automation', weight: '8%' },
      { name: 'Preparing for Automation', weight: '14%' },
      { name: 'Technical Approach to Automation', weight: '30%' },
      { name: 'Generic Automation Architecture', weight: '22%' },
      { name: 'Deployment & Implementation', weight: '12%' },
      { name: 'Reporting & Metrics', weight: '8%' },
      { name: 'Transitioning from Manual to Automated Testing', weight: '6%' },
    ],
    studyResources: [
      { type: 'Official Docs', title: 'ISTQB CT-TAE Syllabus', free: true },
      { type: 'Course', title: 'Test Automation University (free courses)', free: true, note: 'Applitools — covers Playwright, Selenium, Cypress' },
      { type: 'Website', title: 'testautomationu.applitools.com', free: true },
      { type: 'YouTube', title: 'Automation Step by Step — Raghav Pal', free: true },
    ],
    tips: [
      'Understand Generic Automation Architecture (gTAA) model — it features heavily',
      'Know when NOT to automate as well as when to automate',
      'Study the automation ROI calculation approach in the syllabus',
      'Know the difference between data-driven, keyword-driven, and hybrid frameworks',
    ],
    relatedCerts: ['istqb-ctfl', 'playwright-cert'],
    popular: true,
    countryRecognition: ['UK', 'Germany', 'India', 'Netherlands', 'USA'],
  },

  {
    id: 'playwright-cert',
    name: 'Playwright Automation Certification',
    shortName: 'Playwright (TAU)',
    issuer: 'Test Automation University / Applitools',
    issuerLogo: '🎭',
    category: 'Automation',
    difficulty: 'Intermediate',
    duration: '2–4 weeks',
    cost: 'Free',
    validity: 'Non-expiring',
    passMark: 'Complete all course modules',
    questions: 'Quizzes per module',
    format: 'Online video + hands-on labs',
    languages: ['English'],
    description: 'Free certification pathway from Test Automation University covering Playwright for modern web automation. Includes TypeScript, test architecture, Page Object Model, API testing with Playwright, and CI/CD integration.',
    whyGetIt: 'Playwright is the fastest-growing automation framework. Free, recognised credential from a respected platform. Great for portfolio and LinkedIn.',
    careerImpact: 'Required skill for many SDET and automation engineer roles. Demonstrates practical modern automation skill.',
    prerequisites: ['Basic JavaScript/TypeScript knowledge'],
    examTopics: [
      { name: 'Playwright Fundamentals', weight: '25%' },
      { name: 'Locators & Actions', weight: '20%' },
      { name: 'Page Object Model', weight: '20%' },
      { name: 'API Testing', weight: '15%' },
      { name: 'CI/CD Integration', weight: '10%' },
      { name: 'Advanced Features (Fixtures, Parallel)', weight: '10%' },
    ],
    studyResources: [
      { type: 'Official Docs', title: 'Playwright Official Docs — playwright.dev', free: true, note: 'Best documentation of any automation tool' },
      { type: 'Course', title: 'Introduction to Playwright — Test Automation University', free: true },
      { type: 'Course', title: 'Playwright: Web Automation Testing — Udemy (Artem Bondar)', free: false, note: 'Most comprehensive paid course' },
      { type: 'GitHub', title: 'microsoft/playwright — GitHub examples', free: true },
      { type: 'YouTube', title: 'Playwright Tutorial — Naveen AutomationLabs', free: true },
      { type: 'Course', title: 'Playwright with TypeScript — LambdaTest Learning Hub', free: true },
    ],
    tips: [
      'Use TypeScript not JavaScript — it is the standard in professional teams',
      'Master built-in locators: getByRole, getByLabel, getByTestId — avoid CSS selectors',
      'Learn Playwright fixtures for clean test setup/teardown',
      'Practice codegen (npx playwright codegen) to understand how Playwright works',
      'Build a real project — test a public e-commerce site end-to-end',
    ],
    relatedCerts: ['istqb-ct-tae', 'cypress-cert'],
    popular: true,
    countryRecognition: ['Global'],
  },

  {
    id: 'cypress-cert',
    name: 'Cypress Certified Associate',
    shortName: 'Cypress CA',
    issuer: 'Cypress.io',
    issuerLogo: '🌲',
    category: 'Automation',
    difficulty: 'Beginner',
    duration: '2–3 weeks',
    cost: '$75',
    validity: '2 years',
    passMark: '70%',
    questions: '50 multiple choice + practical',
    format: 'Online proctored exam + coding exercise',
    languages: ['English'],
    description: 'Official Cypress certification covering Cypress fundamentals, test writing, assertions, component testing, network stubbing, and CI integration. Validates practical Cypress knowledge for frontend-heavy testing.',
    whyGetIt: 'Official vendor certification directly from Cypress. Valued in JavaScript-heavy organisations (React/Vue/Angular products). Good entry-point automation certification.',
    careerImpact: 'Frontend-focused SDET roles. Strong in US startup market where JavaScript full-stack is prevalent.',
    prerequisites: ['JavaScript fundamentals'],
    examTopics: [
      { name: 'Core Concepts & Configuration', weight: '20%' },
      { name: 'Writing & Running Tests', weight: '30%' },
      { name: 'Assertions & Commands', weight: '20%' },
      { name: 'Network Stubbing & Fixtures', weight: '15%' },
      { name: 'CI/CD Integration', weight: '15%' },
    ],
    studyResources: [
      { type: 'Official Docs', title: 'Cypress Documentation — docs.cypress.io', free: true },
      { type: 'Course', title: 'Cypress — Web Automation Testing — Udemy', free: false },
      { type: 'Course', title: 'Introduction to Cypress — Test Automation University', free: true },
    ],
    tips: [
      'Study the Cypress docs deeply — the exam tests doc knowledge',
      'Understand the difference between cy.intercept() and cy.route()',
      'Practice with the Cypress RealWorld App (open source)',
    ],
    relatedCerts: ['playwright-cert', 'istqb-ct-tae'],
    popular: false,
    countryRecognition: ['USA', 'UK', 'Canada'],
  },

  {
    id: 'postman-api',
    name: 'Postman API Fundamentals Student Expert',
    shortName: 'Postman Expert',
    issuer: 'Postman',
    issuerLogo: '📮',
    category: 'Automation',
    difficulty: 'Beginner',
    duration: '1–2 weeks',
    cost: 'Free',
    validity: 'Non-expiring',
    passMark: 'Complete all workspace tasks',
    questions: 'Practical workspace submission',
    format: 'Hands-on workspace challenges',
    languages: ['English'],
    description: 'Free certification covering Postman for API testing. Covers collections, environments, variables, testing assertions (pm.test), Newman for CI, and API documentation. Completely practical — no multiple choice exam.',
    whyGetIt: 'Postman is installed on virtually every QA engineer\'s machine. Free, practical credential. Good starting point for API testing journey.',
    careerImpact: 'Entry requirement for many QA positions. Strong for mid-level roles where API testing is expected.',
    prerequisites: [],
    examTopics: [
      { name: 'HTTP Basics & REST', weight: '20%' },
      { name: 'Collections & Requests', weight: '25%' },
      { name: 'Variables & Environments', weight: '20%' },
      { name: 'Test Scripts (pm.test)', weight: '25%' },
      { name: 'Newman & CI', weight: '10%' },
    ],
    studyResources: [
      { type: 'Official Docs', title: 'Postman Learning Center — learning.postman.com', free: true },
      { type: 'Course', title: 'Postman Beginner\'s Course — freeCodeCamp YouTube', free: true },
      { type: 'Course', title: 'API Testing with Postman — Udemy (Valentin Despa)', free: false },
    ],
    tips: [
      'Complete the official Postman training workspaces first',
      'Practice writing test scripts with pm.test and pm.expect',
      'Learn to use Collection Runner and Newman for automated runs',
    ],
    relatedCerts: ['istqb-ct-tae', 'playwright-cert'],
    popular: true,
    countryRecognition: ['Global'],
  },

  // ── AI TESTING ───────────────────────────────────────────────────────────

  {
    id: 'ai-quality-engineer',
    name: 'AI Quality Engineer Professional',
    shortName: 'AI QE Pro',
    issuer: 'Ministry of Testing',
    issuerLogo: '🧪',
    category: 'AI Testing',
    difficulty: 'Advanced',
    duration: '8–12 weeks',
    cost: '$299',
    validity: '2 years',
    passMark: '70%',
    questions: 'Portfolio + exam',
    format: 'Portfolio submission + online exam',
    languages: ['English'],
    description: 'Comprehensive certification for QA professionals testing AI/ML systems. Covers LLM testing, RAG evaluation, prompt injection, agentic systems, bias testing, and AI observability. Highly practical with real project submissions.',
    whyGetIt: 'One of the most practical AI QA certifications available. Recognised by AI-native companies. Combines theory with actual AI testing projects.',
    careerImpact: 'AI Quality Engineer roles. 40–60% salary premium over standard QA. High demand at companies deploying LLMs (OpenAI partners, ChatGPT integrators, enterprise AI).',
    prerequisites: ['2+ years QA experience', 'Basic Python or JavaScript'],
    examTopics: [
      { name: 'LLM Fundamentals for Testers', weight: '15%' },
      { name: 'Evaluation & Golden Datasets', weight: '20%' },
      { name: 'Hallucination & Factuality Testing', weight: '20%' },
      { name: 'Safety, Toxicity & Red Teaming', weight: '15%' },
      { name: 'RAG System Testing', weight: '15%' },
      { name: 'Agentic AI Testing', weight: '15%' },
    ],
    studyResources: [
      { type: 'Course', title: 'Testing AI Systems — Ministry of Testing (MoT)', free: false },
      { type: 'Course', title: 'LLM Evaluation — DeepLearning.AI (Andrew Ng)', free: true, note: 'Essential for understanding evaluation metrics' },
      { type: 'Course', title: 'Red Teaming LLM Applications — DeepLearning.AI', free: true },
      { type: 'Website', title: 'lmsys.org — LMSYS Chatbot Arena', free: true },
      { type: 'GitHub', title: 'microsoft/promptflow — Prompt evaluation', free: true },
      { type: 'Official Docs', title: 'OWASP LLM Top 10', free: true },
    ],
    tips: [
      'Build a personal golden dataset and practice LLM-as-judge evaluation',
      'Complete the DeepLearning.AI short courses on LLM evaluation — they are free and excellent',
      'Study the OWASP LLM Top 10 thoroughly — security is a major component',
      'Practice prompt injection attacks on public AI systems (ethically)',
      'Learn to use Promptfoo or LangSmith for systematic prompt testing',
    ],
    relatedCerts: ['istqb-ct-ai', 'google-ml-engineer', 'aws-ai-practitioner'],
    popular: true,
    newBadge: true,
    countryRecognition: ['UK', 'USA', 'Germany', 'Canada', 'Australia'],
  },

  // ── AI/ML ENGINEERING ────────────────────────────────────────────────────

  {
    id: 'google-ml-engineer',
    name: 'Google Professional Machine Learning Engineer',
    shortName: 'Google ML Engineer',
    issuer: 'Google Cloud',
    issuerLogo: '🔵',
    category: 'AI/ML Engineering',
    difficulty: 'Expert',
    duration: '3–6 months study',
    cost: '$200 per attempt',
    validity: '2 years',
    passMark: 'Not disclosed (~70%)',
    questions: '50–60 multiple choice + extended response',
    format: 'Online proctored exam, 2 hours',
    languages: ['English', 'Japanese'],
    description: 'Validates ability to design, build, and operationalise ML models on Google Cloud. Covers ML problem framing, data preparation, model development, evaluation, deployment, and monitoring. Highly respected in the ML industry.',
    whyGetIt: 'One of the most respected ML certifications globally. Signals serious ML engineering capability. Required at many Google Cloud partner companies.',
    careerImpact: 'ML Engineer and AI Engineer roles. $140k–$200k+ in USA. Strong for roles involving MLOps, model deployment, and production ML systems.',
    prerequisites: ['3+ years ML/software experience', 'Python proficiency', 'TensorFlow/PyTorch experience'],
    examTopics: [
      { name: 'Framing ML Problems', weight: '12%' },
      { name: 'Data Preparation & Processing', weight: '20%' },
      { name: 'Feature Engineering', weight: '16%' },
      { name: 'Model Development & Training', weight: '20%' },
      { name: 'Model Evaluation & Improvement', weight: '16%' },
      { name: 'ML Pipelines & Deployment', weight: '16%' },
    ],
    studyResources: [
      { type: 'Official Docs', title: 'Google Cloud ML Engineer Exam Guide', free: true },
      { type: 'Course', title: 'Machine Learning Engineer Learning Path — Google Cloud Skills Boost', free: false, note: 'Official preparation path' },
      { type: 'Course', title: 'Machine Learning Specialization — Coursera (Andrew Ng)', free: false, note: 'Best foundation for ML concepts' },
      { type: 'Course', title: 'ML Engineering for Production (MLOps) — Coursera (DeepLearning.AI)', free: false },
      { type: 'Practice Exam', title: 'Whizlabs Google ML Engineer Practice Tests', free: false },
      { type: 'GitHub', title: 'Google Cloud training samples on GitHub', free: true },
    ],
    tips: [
      'Complete the Google Cloud Skills Boost ML Engineer path before the exam',
      'Understand Vertex AI deeply — it is heavily tested',
      'Study MLOps practices: model versioning, drift detection, A/B testing in production',
      'Know BigQuery ML — it is a unique Google capability frequently tested',
      'Practice the Qwiklabs hands-on labs — the exam is very practical',
    ],
    relatedCerts: ['aws-ml-specialty', 'azure-ai-102', 'istqb-ct-ai'],
    popular: true,
    countryRecognition: ['USA', 'UK', 'Germany', 'India', 'Canada', 'Australia'],
  },

  {
    id: 'aws-ai-practitioner',
    name: 'AWS Certified AI Practitioner',
    shortName: 'AWS AI Practitioner',
    issuer: 'Amazon Web Services',
    issuerLogo: '🟠',
    category: 'Cloud AI',
    difficulty: 'Beginner',
    duration: '4–6 weeks study',
    cost: '$100 per attempt',
    validity: '3 years',
    passMark: '700/1000',
    questions: '65 questions, 90 min',
    format: 'Multiple choice + multiple response, online proctored',
    languages: ['English', 'Japanese', 'Korean', 'Chinese Simplified', 'Portuguese'],
    description: 'Entry-level AWS AI/ML certification. Covers fundamental AI/ML concepts, AWS AI services (SageMaker, Bedrock, Comprehend, Rekognition), responsible AI, and generative AI basics. Ideal first cloud AI certification.',
    whyGetIt: 'Lowest barrier entry into the AWS AI certification path. Demonstrates cloud AI awareness. Good for QA engineers working on AWS-hosted AI applications.',
    careerImpact: 'Differentiates QA engineers moving into AI testing. Valued at AWS partner companies. Pathway to more advanced AWS ML Specialty certification.',
    prerequisites: ['Basic AWS knowledge helpful'],
    examTopics: [
      { name: 'AI & ML Fundamentals', weight: '20%' },
      { name: 'Generative AI & Foundation Models', weight: '24%' },
      { name: 'AWS AI Services', weight: '28%' },
      { name: 'Responsible AI', weight: '14%' },
      { name: 'Security, Compliance & Governance', weight: '14%' },
    ],
    studyResources: [
      { type: 'Official Docs', title: 'AWS AI Practitioner Exam Guide', free: true },
      { type: 'Course', title: 'AWS Certified AI Practitioner — Udemy (Stéphane Maarek)', free: false, note: 'Best seller for AWS certs' },
      { type: 'Course', title: 'AWS Skill Builder — AI Practitioner Learning Plan', free: false },
      { type: 'Practice Exam', title: 'AWS Official Practice Exam — Skill Builder', free: false, note: '$29 — worth it' },
      { type: 'YouTube', title: 'AWS AI Practitioner Free Course — freeCodeCamp', free: true },
    ],
    tips: [
      'Understand Amazon Bedrock and foundation models — heavily weighted',
      'Know the difference between AI, ML, and Generative AI in AWS context',
      'Study responsible AI principles: fairness, explainability, privacy',
      'Memorise key AWS AI services and their use cases',
    ],
    relatedCerts: ['aws-ml-specialty', 'istqb-ct-ai', 'google-ml-engineer'],
    popular: true,
    newBadge: true,
    countryRecognition: ['USA', 'UK', 'India', 'Germany', 'Canada', 'Australia', 'UAE'],
  },

  {
    id: 'aws-ml-specialty',
    name: 'AWS Certified Machine Learning — Specialty',
    shortName: 'AWS ML Specialty',
    issuer: 'Amazon Web Services',
    issuerLogo: '🟠',
    category: 'Cloud AI',
    difficulty: 'Expert',
    duration: '3–5 months study',
    cost: '$300 per attempt',
    validity: '3 years',
    passMark: '750/1000',
    questions: '65 questions, 3 hours',
    format: 'Multiple choice + multiple response, online proctored',
    languages: ['English', 'Japanese', 'Korean'],
    description: 'The highest AWS ML certification. Deep dive into data engineering, exploratory data analysis, ML modelling, ML implementation, and deployment using SageMaker. Requires serious ML engineering experience.',
    whyGetIt: 'Industry gold standard for AWS ML Engineers. Very few people hold it — immediate credibility. Required at AWS partners and premium consulting firms.',
    careerImpact: 'ML Engineer / MLOps Engineer roles at $150k–$220k+ in USA. Significant salary uplift in UK, Germany, and Canada.',
    prerequisites: ['2+ years ML experience', 'AWS experience', 'Pass AWS AI Practitioner or Cloud Practitioner recommended'],
    examTopics: [
      { name: 'Data Engineering', weight: '20%' },
      { name: 'Exploratory Data Analysis', weight: '24%' },
      { name: 'Modelling', weight: '36%' },
      { name: 'ML Implementation & Operations', weight: '20%' },
    ],
    studyResources: [
      { type: 'Official Docs', title: 'AWS ML Specialty Exam Guide', free: true },
      { type: 'Course', title: 'AWS Certified ML Specialty — Udemy (Stéphane Maarek & Frank Kane)', free: false },
      { type: 'Course', title: 'Machine Learning on AWS — AWS Training', free: false },
      { type: 'Book', title: 'Data Science on AWS — Chris Fregly & Antje Barth', free: false },
      { type: 'Practice Exam', title: 'Tutorial Dojo ML Specialty Practice Exams', free: false },
    ],
    tips: [
      'SageMaker is 40%+ of the exam — know it inside out',
      'Understand the full ML pipeline: data preparation, feature engineering, training, tuning, deployment',
      'Study hyperparameter optimisation techniques (SageMaker HPO)',
      'Know when to use XGBoost vs deep learning vs traditional ML algorithms',
      'Practice with AWS labs — the exam is very practical',
    ],
    relatedCerts: ['aws-ai-practitioner', 'google-ml-engineer'],
    popular: false,
    countryRecognition: ['USA', 'UK', 'Germany', 'Canada', 'Australia'],
  },

  {
    id: 'azure-ai-102',
    name: 'Microsoft Azure AI Engineer Associate',
    shortName: 'Azure AI-102',
    issuer: 'Microsoft',
    issuerLogo: '🔷',
    category: 'Cloud AI',
    difficulty: 'Intermediate',
    duration: '6–10 weeks study',
    cost: '$165 per attempt',
    validity: '1 year (annual renewal)',
    passMark: '700/1000',
    questions: '40–60 questions, 100 min',
    format: 'Multiple choice + case studies + labs (online proctored)',
    languages: ['English', 'Japanese', 'Chinese', 'Korean', 'German', 'French'],
    description: 'Validates ability to build, manage, and deploy Azure AI solutions using Azure Cognitive Services, Azure OpenAI Service, Azure AI Search, and Azure Machine Learning. Covers responsible AI principles.',
    whyGetIt: 'Microsoft ecosystem is dominant in enterprise. Azure OpenAI Service is widely used. Strong credential for anyone building AI solutions on Microsoft stack.',
    careerImpact: 'Azure AI Engineer roles at Microsoft partners. Very strong in UK, Germany, and Middle East where Microsoft is dominant. $120k–$180k in USA.',
    prerequisites: ['Basic Azure knowledge (AZ-900 or AZ-104 helpful)', 'Python or C# programming'],
    examTopics: [
      { name: 'Plan & Manage Azure AI Solutions', weight: '15%' },
      { name: 'Implement Decision Support Solutions', weight: '10%' },
      { name: 'Implement Computer Vision Solutions', weight: '15%' },
      { name: 'Implement NLP Solutions', weight: '20%' },
      { name: 'Implement Knowledge Mining & Document Intelligence', weight: '15%' },
      { name: 'Implement Generative AI Solutions (Azure OpenAI)', weight: '25%' },
    ],
    studyResources: [
      { type: 'Official Docs', title: 'Microsoft Learn AI-102 Learning Path', free: true, note: 'Free and comprehensive — official study material' },
      { type: 'Course', title: 'AI-102 Azure AI Engineer — Udemy (Alan Rodrigues)', free: false },
      { type: 'Practice Exam', title: 'MeasureUp AI-102 Practice Tests', free: false, note: 'Official Microsoft practice provider' },
      { type: 'Official Docs', title: 'Azure AI Services Documentation', free: true },
      { type: 'Course', title: 'Azure OpenAI Service — Microsoft Learn', free: true },
    ],
    tips: [
      'Microsoft Learn is free and excellent — complete the official learning path',
      'Azure OpenAI Service is now 25% of the exam — know the API well',
      'Understand responsible AI principles: fairness, reliability, privacy, inclusiveness, transparency, accountability',
      'Annual renewal is just an assessment, not a full retake',
      'Practice with Azure free tier — hands-on labs are essential',
    ],
    relatedCerts: ['aws-ai-practitioner', 'google-ml-engineer', 'istqb-ct-ai'],
    popular: true,
    countryRecognition: ['USA', 'UK', 'Germany', 'India', 'UAE', 'Canada', 'Australia'],
  },

  {
    id: 'deeplearning-nlp',
    name: 'Natural Language Processing Specialization',
    shortName: 'DeepLearning.AI NLP',
    issuer: 'DeepLearning.AI / Coursera',
    issuerLogo: '🧠',
    category: 'AI/ML Engineering',
    difficulty: 'Advanced',
    duration: '4 months (10 hrs/week)',
    cost: '$49/month (Coursera subscription)',
    validity: 'Non-expiring',
    passMark: '80% on all assignments',
    questions: 'Graded assignments + projects',
    format: 'Video lectures + programming assignments',
    languages: ['English'],
    description: 'Andrew Ng\'s DeepLearning.AI NLP specialisation covering sentiment analysis, machine translation, attention mechanisms, transformers, and named entity recognition. Directly relevant for LLM quality engineers.',
    whyGetIt: 'Deep understanding of how LLMs work makes you a vastly better AI QA engineer. You understand why hallucination happens, what embeddings are, and how transformers generate text.',
    careerImpact: 'Foundation for AI Quality Engineer, ML Engineer, and NLP Engineer roles. Essential background knowledge for anyone testing LLM applications.',
    prerequisites: ['Python', 'Basic ML (Coursera ML Specialization recommended first)'],
    examTopics: [
      { name: 'Classification, Vector Spaces & Embeddings', weight: '25%' },
      { name: 'Probabilistic Models (N-grams, HMM)', weight: '25%' },
      { name: 'Sequence Models (RNN, LSTM)', weight: '25%' },
      { name: 'Attention Mechanisms & Transformers', weight: '25%' },
    ],
    studyResources: [
      { type: 'Course', title: 'NLP Specialization — DeepLearning.AI on Coursera', free: false, note: 'Audit for free, pay for certificate' },
      { type: 'Course', title: 'LLM Evaluation & LLMOps — DeepLearning.AI short courses', free: true },
      { type: 'Website', title: 'Hugging Face NLP Course — huggingface.co/learn', free: true, note: 'Excellent free alternative' },
      { type: 'Book', title: 'Natural Language Processing with Transformers — Tunstall et al.', free: false },
      { type: 'YouTube', title: 'Andrej Karpathy — Let\'s build GPT (YouTube)', free: true, note: 'Deep understanding of how GPT works' },
    ],
    tips: [
      'Complete the ML Specialization first if you\'re new to ML',
      'Hugging Face NLP course is free and more up-to-date for transformer-based models',
      'Karpathy\'s "Let\'s build GPT" YouTube video is the single best resource for understanding LLMs',
    ],
    relatedCerts: ['google-ml-engineer', 'azure-ai-102', 'istqb-ct-ai'],
    popular: false,
    countryRecognition: ['Global'],
  },

  {
    id: 'huggingface-cert',
    name: 'Hugging Face Agents Course Certificate',
    shortName: 'HuggingFace Agents',
    issuer: 'Hugging Face',
    issuerLogo: '🤗',
    category: 'AI Testing',
    difficulty: 'Intermediate',
    duration: '4–6 weeks',
    cost: 'Free',
    validity: 'Non-expiring',
    passMark: 'Complete all modules + final project',
    questions: 'Quizzes + final agent project',
    format: 'Self-paced online course + hands-on project',
    languages: ['English'],
    description: 'Free Hugging Face course on building and evaluating AI agents. Covers agent frameworks, tool use, memory, multi-agent systems, and safety evaluation. Directly relevant for testing agentic AI systems.',
    whyGetIt: 'Free, highly practical, and directly relevant to the fastest-growing area of AI development. Understanding how agents work is essential for testing them.',
    careerImpact: 'AI Quality Engineer specialising in agentic systems. Strong portfolio piece for AI testing roles.',
    prerequisites: ['Python', 'Basic LLM concepts'],
    examTopics: [
      { name: 'Introduction to AI Agents', weight: '20%' },
      { name: 'Tools & Function Calling', weight: '20%' },
      { name: 'Agent Frameworks (LangGraph, Smolagents)', weight: '25%' },
      { name: 'Multi-Agent Systems', weight: '20%' },
      { name: 'Safety & Evaluation', weight: '15%' },
    ],
    studyResources: [
      { type: 'Course', title: 'Hugging Face Agents Course — huggingface.co/learn', free: true },
      { type: 'Official Docs', title: 'LangGraph Documentation', free: true },
      { type: 'Course', title: 'Building Agentic RAG — DeepLearning.AI', free: true },
      { type: 'GitHub', title: 'huggingface/smolagents', free: true },
    ],
    tips: [
      'Complete the Hugging Face NLP course first for context',
      'Build and test a real agent during the course — the hands-on project is the certification',
      'Focus on understanding how tool calling works — key for MCP and agentic testing',
    ],
    relatedCerts: ['istqb-ct-ai', 'ai-quality-engineer', 'azure-ai-102'],
    popular: true,
    newBadge: true,
    countryRecognition: ['Global'],
  },

  // ── SECURITY ─────────────────────────────────────────────────────────────

  {
    id: 'comptia-security',
    name: 'CompTIA Security+',
    shortName: 'Security+',
    issuer: 'CompTIA',
    issuerLogo: '🔒',
    category: 'Security',
    difficulty: 'Intermediate',
    duration: '8–12 weeks study',
    cost: '$392 per attempt',
    validity: '3 years',
    passMark: '750/900',
    questions: 'Max 90 questions, 90 min',
    format: 'Multiple choice + performance-based questions',
    languages: ['English', 'Japanese'],
    description: 'Baseline cybersecurity certification covering threats, vulnerabilities, technologies, tools, identity management, risk management, and cryptography. DoD-approved, widely recognised across industries.',
    whyGetIt: 'Required for security testing roles and government contracts (US DoD 8570 mandate). Validates security knowledge for QA engineers doing penetration testing or security verification.',
    careerImpact: 'Security QA, Penetration Tester, and Security Analyst roles. Government and defence sector prerequisite in USA. 15–25% salary premium over non-security QA.',
    prerequisites: ['CompTIA Network+ recommended', '2 years IT experience helpful'],
    examTopics: [
      { name: 'Attacks, Threats & Vulnerabilities', weight: '24%' },
      { name: 'Architecture & Design', weight: '21%' },
      { name: 'Implementation (PKI, protocols)', weight: '25%' },
      { name: 'Operations & Incident Response', weight: '16%' },
      { name: 'Governance, Risk & Compliance', weight: '14%' },
    ],
    studyResources: [
      { type: 'Course', title: 'CompTIA Security+ (SY0-701) — Professor Messer', free: true, note: 'Best free Security+ resource' },
      { type: 'Book', title: 'CompTIA Security+ Study Guide — Mike Chapple & David Seidl', free: false },
      { type: 'Practice Exam', title: 'Darril Gibson Security+ Practice Tests', free: false },
      { type: 'YouTube', title: 'Professor Messer Security+ Course — YouTube', free: true },
    ],
    tips: [
      'Professor Messer\'s free YouTube course is excellent and up to date',
      'Focus on performance-based questions (PBQ) — many candidates run out of time',
      'Understand cryptography concepts thoroughly — tested heavily',
      'Learn the security frameworks: NIST, ISO 27001, CIS',
    ],
    relatedCerts: ['istqb-ctfl', 'aws-ai-practitioner'],
    popular: false,
    countryRecognition: ['USA', 'UK', 'Canada', 'Australia', 'Germany'],
  },

  // ── AGILE & PROCESS ──────────────────────────────────────────────────────

  {
    id: 'safe-agilist',
    name: 'SAFe Agilist (SA)',
    shortName: 'SAFe SA',
    issuer: 'Scaled Agile Inc.',
    issuerLogo: '🔄',
    category: 'Agile & Process',
    difficulty: 'Intermediate',
    duration: '2–4 weeks study + 2-day training',
    cost: '$995 (includes 2-day training + exam)',
    validity: '1 year (annual renewal $100)',
    passMark: '77%',
    questions: '45 questions, 90 min',
    format: 'Multiple choice, online proctored',
    languages: ['English'],
    description: 'Entry-level Scaled Agile Framework certification. Covers SAFe principles, Agile Release Trains, PI Planning, lean-agile mindset, and team-level agile practices at enterprise scale.',
    whyGetIt: 'SAFe is widely adopted in large enterprises (banking, government, insurance). Required for many QA Lead roles in organisations running SAFe. ART (Agile Release Train) testing practices are directly relevant.',
    careerImpact: 'QA Lead and Test Manager roles in SAFe organisations. Strong in UK, Australian government, and US enterprise. Annual renewal maintains relevance.',
    prerequisites: ['5+ days Agile experience (practical or training)'],
    examTopics: [
      { name: 'SAFe Principles & Mindset', weight: '25%' },
      { name: 'Team-level Agile (Scrum/Kanban)', weight: '20%' },
      { name: 'Program-level (ART, PI Planning)', weight: '30%' },
      { name: 'Lean-Agile Leadership', weight: '15%' },
      { name: 'Continuous Delivery Pipeline', weight: '10%' },
    ],
    studyResources: [
      { type: 'Official Docs', title: 'Scaled Agile Framework — scaledagileframework.com', free: true, note: 'The website IS the study guide' },
      { type: 'Course', title: 'Leading SAFe — Official 2-day course (required)', free: false },
      { type: 'Practice Exam', title: 'SAFe Agilist Practice Test — Scaled Agile', free: true, note: 'Available after course registration' },
    ],
    tips: [
      'Attend the official 2-day Leading SAFe class — it includes exam prep',
      'Study the SAFe website thoroughly — all exam answers come from it',
      'Understand PI Planning — it is the heart of SAFe and heavily tested',
      'Annual renewal is just a 30-question assessment — easy with job experience',
    ],
    relatedCerts: ['istqb-ct-at', 'pmp'],
    popular: false,
    countryRecognition: ['USA', 'UK', 'Germany', 'Australia', 'Canada'],
  },

];

export const CERT_CATEGORIES: CertCategory[] = [
  'QA Fundamentals', 'Automation', 'AI Testing', 'AI/ML Engineering', 'Cloud AI', 'Security', 'Agile & Process',
];

export const CERT_DIFFICULTY_ORDER: CertDifficulty[] = ['Beginner', 'Intermediate', 'Advanced', 'Expert'];

export const difficultyColor: Record<CertDifficulty, string> = {
  Beginner: '#10b981',
  Intermediate: '#3b82f6',
  Advanced: '#f59e0b',
  Expert: '#ef4444',
};

export const categoryColor: Record<CertCategory, string> = {
  'QA Fundamentals': '#6366f1',
  'Automation': '#10b981',
  'AI Testing': '#a855f7',
  'AI/ML Engineering': '#ec4899',
  'Cloud AI': '#f59e0b',
  'Security': '#ef4444',
  'Agile & Process': '#3b82f6',
};

export const resourceTypeIcon: Record<StudyResource['type'], string> = {
  'Official Docs': '📄',
  'Book': '📚',
  'Course': '🎓',
  'Practice Exam': '📝',
  'YouTube': '▶️',
  'GitHub': '💻',
  'Website': '🌐',
};

// Suggested learning roadmaps
export const roadmaps = [
  {
    id: 'junior-to-mid',
    title: 'Junior QA → Mid QA',
    icon: '🌱',
    color: '#10b981',
    steps: ['istqb-ctfl', 'postman-api', 'playwright-cert'],
    description: 'Foundation certification + API testing + automation basics',
  },
  {
    id: 'mid-to-senior',
    title: 'Mid QA → Senior SDET',
    icon: '⚡',
    color: '#6366f1',
    steps: ['istqb-ctal-ta', 'istqb-ct-tae', 'cypress-cert'],
    description: 'Advanced test design + automation engineering certification',
  },
  {
    id: 'qa-to-ai-engineer',
    title: 'QA → AI Quality Engineer',
    icon: '🤖',
    color: '#a855f7',
    steps: ['istqb-ct-ai', 'aws-ai-practitioner', 'ai-quality-engineer', 'huggingface-cert'],
    description: 'The fastest path from traditional QA to AI testing specialist',
  },
  {
    id: 'lead-manager',
    title: 'Senior QA → QA Manager',
    icon: '👑',
    color: '#f59e0b',
    steps: ['istqb-ctal-tm', 'safe-agilist', 'csqe'],
    description: 'Test management + Agile process + quality management',
  },
  {
    id: 'ml-engineer',
    title: 'QA → ML/AI Engineer',
    icon: '🧠',
    color: '#ec4899',
    steps: ['aws-ai-practitioner', 'azure-ai-102', 'google-ml-engineer', 'aws-ml-specialty'],
    description: 'Full cloud AI engineer certification pathway',
  },
];
