export interface RouteStep {
  certId: string;
  certName: string;
  why: string;
  duration: string;
  cost: string;
  costUSD: number;
  skillsGained: string[];
  unlocks: string[];
  icon: string;
}

export interface CertRoute {
  id: string;
  title: string;
  subtitle: string;
  icon: string;
  color: string;
  targetRole: string;
  salaryRange: string;
  totalCost: string;
  totalCostUSD: number;
  totalTime: string;
  difficulty: string;
  countriesHighDemand: string[];
  steps: RouteStep[];
  summary: string;
  prerequisites: string[];
  nextRoutes: string[];
}

export const certRoutes: CertRoute[] = [
  {
    id: 'manual-to-automation',
    title: 'Manual Tester → Automation Engineer',
    subtitle: 'The most travelled QA career path worldwide',
    icon: '🚀',
    color: '#6366f1',
    targetRole: 'Automation QA Engineer / SDET',
    salaryRange: '$70k–$130k (US) | ₹8–20 LPA (India) | £50–80k (UK)',
    totalCost: '$450–$700',
    totalCostUSD: 575,
    totalTime: '8–12 months',
    difficulty: 'Intermediate',
    countriesHighDemand: ['🇮🇳 India', '🇺🇸 USA', '🇬🇧 UK', '🇦🇺 Australia', '🇨🇦 Canada', '🇵🇱 Poland'],
    prerequisites: ['6+ months manual testing experience', 'Basic understanding of SDLC', 'Some exposure to bug tracking tools'],
    summary: 'Transform from a manual tester into a highly employable automation engineer. This path builds the foundational credibility (ISTQB), core automation skills (Playwright), and API testing mastery that employers worldwide demand. Estimated 8–12 months at 1–2 hours/day study time.',
    steps: [
      {
        certId: 'istqb-ctfl',
        certName: 'ISTQB Foundation Level (CTFL)',
        why: 'The universal baseline that proves you understand testing principles. Required or preferred in 70% of job postings outside the US. Opens doors in India, UK, Europe, UAE, Australia.',
        duration: '4–6 weeks',
        cost: '$180–$250',
        costUSD: 215,
        skillsGained: ['Test design techniques', 'Test management', 'Bug lifecycle', 'Agile testing', 'Risk-based testing'],
        unlocks: ['Junior QA Engineer roles', 'ISTQB Advanced eligibility', 'Recognition in 120+ countries'],
        icon: '📋',
      },
      {
        certId: 'playwright-tau',
        certName: 'Playwright Automation (Test Automation University)',
        why: 'Playwright has overtaken Selenium as the industry default in 2024–25. Free certification with massive employer recognition. Pairs perfectly with ISTQB foundation.',
        duration: '3–4 weeks',
        cost: '$0 (Free)',
        costUSD: 0,
        skillsGained: ['Playwright setup and config', 'Page Object Model', 'CI/CD integration', 'TypeScript/JavaScript', 'API testing with Playwright'],
        unlocks: ['Automation Engineer title', 'Mid-level QA roles', 'CI/CD pipelines'],
        icon: '🎭',
      },
      {
        certId: 'postman-expert',
        certName: 'Postman API Certification',
        why: 'API testing is now mandatory at every level. Postman\'s free certification demonstrates practical API skills and is globally recognised. Most automation roles require API testing.',
        duration: '2–3 weeks',
        cost: '$0 (Free)',
        costUSD: 0,
        skillsGained: ['REST API testing', 'Collection automation', 'Newman CLI', 'Environment variables', 'Contract testing basics'],
        unlocks: ['API QA Engineer roles', 'Backend testing projects', 'Higher salary bands'],
        icon: '📬',
      },
      {
        certId: 'aws-ai-practitioner',
        certName: 'AWS AI Practitioner (AIF-C01)',
        why: 'Cloud testing is now expected at mid-senior level. AWS is the dominant cloud platform. This cert future-proofs your profile and opens DevOps-adjacent QA opportunities.',
        duration: '4–6 weeks',
        cost: '$150 (exam) + $0–$100 (study)',
        costUSD: 200,
        skillsGained: ['AWS core services', 'Cloud-based test environments', 'AI service basics', 'Infrastructure for QA'],
        unlocks: ['Cloud QA Engineer roles', 'DevOps QA pathways', 'Senior level eligibility'],
        icon: '☁️',
      },
    ],
    nextRoutes: ['sdet-track', 'ai-quality-engineer'],
  },
  {
    id: 'sdet-track',
    title: 'QA Engineer → SDET',
    subtitle: 'Engineer-grade testing skills for higher compensation',
    icon: '⚡',
    color: '#10b981',
    targetRole: 'Software Development Engineer in Test (SDET)',
    salaryRange: '$100k–$180k (US) | ₹12–30 LPA (India) | £60–100k (UK)',
    totalCost: '$600–$900',
    totalCostUSD: 750,
    totalTime: '10–14 months',
    difficulty: 'Advanced',
    countriesHighDemand: ['🇺🇸 USA', '🇬🇧 UK', '🇳🇱 Netherlands', '🇨🇦 Canada', '🇸🇬 Singapore'],
    prerequisites: ['2+ years QA experience', 'Basic programming in any language', 'Familiarity with Git', 'Understanding of CI/CD'],
    summary: 'SDETs earn 40–80% more than QA Engineers for the same years of experience. This path builds genuine software engineering depth — framework design, TypeScript/Python mastery, CI/CD architecture, and performance testing — that earns the SDET title at FAANG, fintech, and top product companies.',
    steps: [
      {
        certId: 'istqb-ctal-tae',
        certName: 'ISTQB Advanced Test Automation Engineer (CT-TAE)',
        why: 'The gold standard for automation architecture credentials. Covers test framework design, risk-based automation strategy, CI integration. Required for SDET and senior automation roles in European and UK markets.',
        duration: '6–8 weeks',
        cost: '$250–$350',
        costUSD: 300,
        skillsGained: ['Test automation architecture', 'Framework design patterns', 'Keyword-driven testing', 'CI/CD test integration', 'Risk-based automation decisions'],
        unlocks: ['Senior Automation Engineer', 'SDET title', 'Test Architect pathway'],
        icon: '🏗️',
      },
      {
        certId: 'playwright-tau',
        certName: 'Playwright Advanced + TypeScript Mastery',
        why: 'Deep Playwright knowledge is the core SDET skill in 2025. TypeScript is the language of modern web automation. Building custom reporters and plugins demonstrates engineering-level thinking.',
        duration: '4–6 weeks',
        cost: '$0 (Free)',
        costUSD: 0,
        skillsGained: ['Advanced selectors and fixtures', 'Custom test reporters', 'Visual regression testing', 'Mobile emulation', 'TypeScript generics for page objects'],
        unlocks: ['Test Infrastructure Engineer', 'Framework ownership', 'Principal Engineer track'],
        icon: '🎭',
      },
      {
        certId: 'k6-performance',
        certName: 'k6 Performance Testing (Grafana)',
        why: 'Performance testing is a core SDET skill gap that commands a salary premium. k6 is the modern tool replacing JMeter in cloud-native stacks. Free certification from Grafana/k6.',
        duration: '3–4 weeks',
        cost: '$0 (Free)',
        costUSD: 0,
        skillsGained: ['Load test scripting', 'Threshold-based pass/fail', 'CI/CD integration', 'Cloud load testing', 'Metrics analysis (Grafana)'],
        unlocks: ['Performance QA title', 'SRE-adjacent roles', 'Reliability engineering'],
        icon: '📊',
      },
      {
        certId: 'aws-devops-pro',
        certName: 'AWS Developer Associate (DVA-C02)',
        why: 'SDETs are expected to own CI/CD pipelines, containerised test environments, and cloud-based test execution. AWS Developer Associate validates the engineering depth that separates SDETs from automation engineers.',
        duration: '6–8 weeks',
        cost: '$300 (exam + study)',
        costUSD: 300,
        skillsGained: ['AWS Lambda, ECS, CodePipeline', 'IaC for test environments', 'Serverless testing', 'Secrets management', 'CloudWatch observability'],
        unlocks: ['DevOps QA Engineer', 'Principal SDET', 'Tech lead eligibility'],
        icon: '☁️',
      },
    ],
    nextRoutes: ['ai-quality-engineer', 'automation-architect'],
  },
  {
    id: 'ai-quality-engineer',
    title: 'QA Engineer → AI Quality Engineer',
    subtitle: 'The fastest-growing and highest-paying QA specialisation',
    icon: '🤖',
    color: '#a855f7',
    targetRole: 'AI Quality Engineer / ML Test Engineer',
    salaryRange: '$140k–$250k (US) | ₹20–50 LPA (India) | £90–140k (UK)',
    totalCost: '$700–$1,100',
    totalCostUSD: 900,
    totalTime: '10–15 months',
    difficulty: 'Expert',
    countriesHighDemand: ['🇺🇸 USA', '🇬🇧 UK', '🇸🇬 Singapore', '🇨🇦 Canada', '🇳🇱 Netherlands'],
    prerequisites: ['3+ years QA or engineering experience', 'Python basics', 'Understanding of ML concepts', 'API testing proficiency'],
    summary: 'AI Quality Engineering is growing 200% YoY with critical talent shortage. Companies like OpenAI, Anthropic, Google DeepMind, and every major enterprise AI team desperately need engineers who can test LLMs, validate AI pipelines, and prevent AI failures. This path combines ISTQB\'s new CT-AI certification with practical ML testing tools.',
    steps: [
      {
        certId: 'istqb-ct-ai',
        certName: 'ISTQB CT-AI (Certified Tester AI Testing)',
        why: 'The world\'s first internationally recognised AI testing certification. Covers LLM testing methodology, bias testing, ML pipeline validation, AI-specific risk categories. Launched 2023 — already required by European enterprises.',
        duration: '6–8 weeks',
        cost: '$250–$350',
        costUSD: 300,
        skillsGained: ['LLM evaluation methodology', 'AI bias and fairness testing', 'ML pipeline testing', 'AI risk categories', 'Responsible AI quality framework'],
        unlocks: ['AI QA Engineer roles', 'LLM testing projects', 'AI compliance roles'],
        icon: '🧠',
      },
      {
        certId: 'google-ml-engineer',
        certName: 'Google Professional ML Engineer',
        why: 'Technical depth in ML systems is what separates AI QE candidates. Understanding training pipelines, model evaluation metrics, and deployment patterns is essential for testing AI at scale.',
        duration: '8–10 weeks',
        cost: '$200 (exam) + $100–$200 (study)',
        costUSD: 350,
        skillsGained: ['ML system design', 'Model training and evaluation', 'Vertex AI', 'Feature stores', 'MLOps pipelines'],
        unlocks: ['MLOps QA Engineer', 'AI Platform Testing', 'Staff AI QE roles'],
        icon: '🔬',
      },
      {
        certId: 'azure-ai-102',
        certName: 'Azure AI Engineer Associate (AI-102)',
        why: 'Many enterprise AI systems are Azure-based (Copilot, Azure OpenAI, Cognitive Services). Azure AI-102 validates understanding of the AI services QA engineers must test in enterprise environments.',
        duration: '4–6 weeks',
        cost: '$165 (exam) + $50 (study)',
        costUSD: 215,
        skillsGained: ['Azure OpenAI Service testing', 'Cognitive Services', 'AI safety evaluation', 'Responsible AI principles', 'MLflow and Azure ML'],
        unlocks: ['Enterprise AI QA roles', 'Azure AI Platform testing', 'Microsoft partner companies'],
        icon: '☁️',
      },
    ],
    nextRoutes: ['security-testing', 'automation-architect'],
  },
  {
    id: 'junior-to-senior',
    title: 'Junior QA → Senior QA Engineer',
    subtitle: 'The 2-year structured career acceleration plan',
    icon: '📈',
    color: '#f59e0b',
    targetRole: 'Senior QA Engineer',
    salaryRange: '$110k–$160k (US) | ₹12–22 LPA (India) | £60–90k (UK)',
    totalCost: '$500–$800',
    totalCostUSD: 650,
    totalTime: '18–24 months',
    difficulty: 'Intermediate',
    countriesHighDemand: ['🇮🇳 India', '🇺🇸 USA', '🇬🇧 UK', '🇦🇺 Australia', '🇩🇪 Germany', '🇵🇱 Poland'],
    prerequisites: ['6–18 months as Junior QA', 'ISTQB Foundation or equivalent experience', 'Basic automation exposure'],
    summary: 'The structured path from Junior to Senior QA in 2 years. Focuses on the credentialing, automation skills, and broadening into API and cloud testing that hiring managers specifically look for when promoting juniors. With ISTQB Advanced, Playwright, and API mastery, a Senior QA title and 2x salary are achievable.',
    steps: [
      {
        certId: 'istqb-ctfl',
        certName: 'ISTQB Foundation Level (if not already held)',
        why: 'Non-negotiable baseline. If you don\'t have it yet, get it now. It\'s the universal credential that justifies pay rises and promotions in every market.',
        duration: '4–6 weeks',
        cost: '$180–$250',
        costUSD: 215,
        skillsGained: ['Testing fundamentals', 'Test design techniques', 'Test management', 'Defect lifecycle'],
        unlocks: ['Mid-level QA eligibility', 'European market jobs', 'ISTQB Advanced path'],
        icon: '📋',
      },
      {
        certId: 'playwright-tau',
        certName: 'Playwright Test Automation',
        why: 'Automation skills are the primary differentiator between Junior and Senior QA. Playwright is the skill employers want most in 2025.',
        duration: '3–4 weeks',
        cost: '$0 (Free)',
        costUSD: 0,
        skillsGained: ['Browser automation', 'Page Object Model', 'CI integration', 'API testing'],
        unlocks: ['Automation QA title', 'Senior eligibility', 'SDET pathway'],
        icon: '🎭',
      },
      {
        certId: 'istqb-ctal-tm',
        certName: 'ISTQB Advanced Test Manager (CTAL-TM)',
        why: 'Test management skills are what distinguish Senior QAs who can own a test strategy from those who just execute test cases. Opens the lead and manager pathway.',
        duration: '8–10 weeks',
        cost: '$250–$380',
        costUSD: 315,
        skillsGained: ['Test strategy design', 'Risk management', 'Test metrics and reporting', 'Team coordination', 'Stakeholder management'],
        unlocks: ['Senior QA Engineer title', 'QA Lead pathway', 'Test Manager pathway'],
        icon: '📊',
      },
    ],
    nextRoutes: ['sdet-track', 'qa-lead-manager', 'ai-quality-engineer'],
  },
  {
    id: 'qa-lead-manager',
    title: 'Senior QA → QA Lead / Manager',
    subtitle: 'Leadership credentials for the management track',
    icon: '👑',
    color: '#d97706',
    targetRole: 'QA Lead / QA Manager / Test Manager',
    salaryRange: '$130k–$200k (US) | ₹18–35 LPA (India) | £80–120k (UK)',
    totalCost: '$800–$1,200',
    totalCostUSD: 1000,
    totalTime: '12–18 months',
    difficulty: 'Advanced',
    countriesHighDemand: ['🇺🇸 USA', '🇬🇧 UK', '🇦🇺 Australia', '🇨🇦 Canada', '🇩🇪 Germany', '🇸🇬 Singapore'],
    prerequisites: ['3–5 years QA experience', 'ISTQB Foundation minimum', 'Experience leading a small team or project', 'Stakeholder communication experience'],
    summary: 'The management track requires a different credential set — leadership frameworks, agile at scale, and strategic test management. SAFe Agilist + ISTQB Advanced Test Manager is the winning combination for QA Lead and Manager roles at large organisations.',
    steps: [
      {
        certId: 'istqb-ctal-tm',
        certName: 'ISTQB Advanced Test Manager (CTAL-TM)',
        why: 'The premier Test Manager certification worldwide. Covers all aspects of managing a QA function: strategy, planning, metrics, risk, teams. Required or preferred for Test Manager roles in EU, UK, Australia.',
        duration: '8–10 weeks',
        cost: '$250–$380',
        costUSD: 315,
        skillsGained: ['Enterprise test strategy', 'Resource planning', 'Metrics and KPIs', 'Risk-based testing', 'Incident management'],
        unlocks: ['Test Manager title', 'QA Lead roles', 'Director pathway'],
        icon: '📊',
      },
      {
        certId: 'safe-agilist',
        certName: 'SAFe Agilist (SA) — Scaled Agile Framework',
        why: 'Enterprise QA teams operate in SAFe environments. SAFe Agilist validates you can lead quality within PI Planning, Agile Release Trains, and program-level testing. Critical for QA Lead roles at large companies.',
        duration: '2 days (course) + 1 week prep',
        cost: '$895 (includes exam)',
        costUSD: 895,
        skillsGained: ['SAFe principles', 'PI Planning facilitation', 'Agile Release Train quality', 'Lean-Agile leadership', 'Release planning'],
        unlocks: ['QA Lead in enterprise', 'SAFe quality consulting', 'Program-level QA ownership'],
        icon: '🔄',
      },
      {
        certId: 'istqb-ct-ai',
        certName: 'ISTQB CT-AI (optional but high-impact for 2025+)',
        why: 'Managers who understand AI testing are being promoted to lead AI quality initiatives. This differentiates you as a forward-thinking quality leader vs a traditional test manager.',
        duration: '4–6 weeks',
        cost: '$250–$350',
        costUSD: 300,
        skillsGained: ['AI quality strategy', 'LLM risk assessment', 'AI testing governance', 'Team upskilling in AI'],
        unlocks: ['Head of AI Quality', 'VP Quality Engineering', 'AI quality consulting'],
        icon: '🧠',
      },
    ],
    nextRoutes: ['ai-quality-engineer', 'automation-architect'],
  },
  {
    id: 'security-testing',
    title: 'QA Engineer → Security Test Engineer',
    subtitle: 'High-demand specialist track with 40% salary premium',
    icon: '🔐',
    color: '#ef4444',
    targetRole: 'Security Test Engineer / AppSec QA',
    salaryRange: '$110k–$165k (US) | ₹14–25 LPA (India) | £70–110k (UK)',
    totalCost: '$800–$1,200',
    totalCostUSD: 1000,
    totalTime: '12–18 months',
    difficulty: 'Advanced',
    countriesHighDemand: ['🇺🇸 USA', '🇬🇧 UK', '🇦🇺 Australia', '🇨🇦 Canada', '🇸🇬 Singapore', '🇦🇪 UAE'],
    prerequisites: ['2+ years QA experience', 'API testing proficiency', 'Basic networking understanding', 'Familiarity with OWASP'],
    summary: 'Security testing bridges QA and cybersecurity — the rarest and most valuable combination in the job market. With AppSec being integrated into CI/CD pipelines (shift-left security), companies need QA engineers who can run DAST/SAST tools, test authentication flows, and validate OWASP Top 10 remediations.',
    steps: [
      {
        certId: 'comptia-security-plus',
        certName: 'CompTIA Security+ (SY0-701)',
        why: 'The universal entry-point security certification. Validates security fundamentals, attack types, compliance frameworks. Required baseline for any security-focused role. Recognised globally, vendor-neutral.',
        duration: '8–10 weeks',
        cost: '$370 (exam) + $100 (study)',
        costUSD: 470,
        skillsGained: ['Threat identification', 'Network security', 'Cryptography basics', 'Compliance frameworks', 'Incident response'],
        unlocks: ['Security-aware QA roles', 'AppSec QA positions', 'Government/defence sector'],
        icon: '🛡️',
      },
      {
        certId: 'owasp-practitioner',
        certName: 'OWASP Web Application Security Testing (WAST)',
        why: 'OWASP Top 10 is the global standard for web application security testing. Every security test engineer must demonstrate OWASP knowledge. Free learning + community certification.',
        duration: '4–6 weeks',
        cost: '$0–$100',
        costUSD: 50,
        skillsGained: ['OWASP Top 10 exploitation', 'Burp Suite basics', 'SQL injection testing', 'XSS vulnerability testing', 'Auth bypass techniques'],
        unlocks: ['Penetration tester pathway', 'Security regression testing', 'Bug bounty programs'],
        icon: '🔓',
      },
      {
        certId: 'aws-security-specialty',
        certName: 'AWS Security Specialty (or Azure SC-100)',
        why: 'Cloud security testing is where the high-paying work is. AWS/Azure security certifications validate the ability to test IAM, S3 bucket exposure, API Gateway security, and cloud-native vulnerabilities.',
        duration: '8–12 weeks',
        cost: '$300 (exam + study)',
        costUSD: 300,
        skillsGained: ['Cloud IAM testing', 'S3 and network security', 'Security Hub and GuardDuty', 'Compliance auditing', 'Incident response testing'],
        unlocks: ['Cloud Security QA', 'DevSecOps Engineer', 'Principal AppSec Engineer'],
        icon: '☁️',
      },
    ],
    nextRoutes: ['ai-quality-engineer', 'sdet-track'],
  },
  {
    id: 'automation-architect',
    title: 'Senior/Lead QA → Test Automation Architect',
    subtitle: 'Framework design and enterprise-scale quality infrastructure',
    icon: '🏗️',
    color: '#0ea5e9',
    targetRole: 'Test Automation Architect / Principal SDET',
    salaryRange: '$140k–$200k (US) | ₹25–50 LPA (India) | £100–140k (UK)',
    totalCost: '$1,000–$1,600',
    totalCostUSD: 1300,
    totalTime: '18–24 months',
    difficulty: 'Expert',
    countriesHighDemand: ['🇺🇸 USA', '🇬🇧 UK', '🇳🇱 Netherlands', '🇸🇬 Singapore', '🇦🇺 Australia'],
    prerequisites: ['5+ years QA/SDET experience', 'Multiple automation frameworks experience', 'CI/CD pipeline ownership', 'Team leadership experience'],
    summary: 'The Automation Architect defines how an organisation does quality at scale. This path builds the credentialing, cloud-native testing, and framework design knowledge to justify Principal SDET, Staff Engineer, and Test Architect titles at top tech companies.',
    steps: [
      {
        certId: 'istqb-ctal-tae',
        certName: 'ISTQB Advanced Test Automation Engineer (CT-TAE)',
        why: 'The only globally recognised certification specifically for automation architecture. Covers model-based testing, CI/CD framework design, multi-layer test automation. The Architect\'s baseline credential.',
        duration: '6–8 weeks',
        cost: '$250–$380',
        costUSD: 315,
        skillsGained: ['Automation architecture patterns', 'Model-based test generation', 'Multi-layer automation strategy', 'Framework comparison and selection', 'Automation ROI analysis'],
        unlocks: ['Test Architect title', 'Framework ownership at scale', 'Principal SDET pathway'],
        icon: '🏗️',
      },
      {
        certId: 'aws-solutions-architect',
        certName: 'AWS Solutions Architect Associate (SAA-C03)',
        why: 'Architects design and own the infrastructure their test frameworks run on. Cloud infrastructure knowledge is essential for ephemeral test environments, parallel execution at scale, and cost-optimised test pipelines.',
        duration: '8–12 weeks',
        cost: '$300 (exam + study)',
        costUSD: 300,
        skillsGained: ['AWS architecture patterns', 'Containerised test execution (ECS/EKS)', 'Cost-optimised parallel testing', 'Serverless test infrastructure', 'Multi-region test environments'],
        unlocks: ['Platform Engineering QA', 'DevOps/DORA metrics ownership', 'CTO-adjacent visibility'],
        icon: '☁️',
      },
      {
        certId: 'google-ml-engineer',
        certName: 'AI-Assisted Testing Fundamentals + ISTQB CT-AI',
        why: 'Future-proof: Architects who understand AI-assisted test generation, AI-driven test prioritisation, and autonomous testing agents will design the test infrastructure of the next decade.',
        duration: '6–8 weeks',
        cost: '$250–$350',
        costUSD: 300,
        skillsGained: ['AI test generation', 'Autonomous test execution', 'LLM-driven test prioritisation', 'AI quality governance', 'Test intelligence platforms'],
        unlocks: ['Head of Quality Engineering', 'VP Quality Engineering', 'Test Platform startup founding'],
        icon: '🤖',
      },
      {
        certId: 'safe-agilist',
        certName: 'SAFe Agilist + LeSS Practitioner',
        why: 'Architects present to CTOs, VPs, and Product. SAFe/LeSS validates you can communicate quality strategy in the language of enterprise agile transformation — essential for organisational influence.',
        duration: '2 weeks',
        cost: '$895 (SAFe)',
        costUSD: 895,
        skillsGained: ['Quality at enterprise scale', 'PI Planning integration', 'Test community of practice', 'Quality metrics for C-suite', 'Test COE establishment'],
        unlocks: ['Quality Director', 'Head of Engineering Enablement', 'CTO advisory roles'],
        icon: '🔄',
      },
    ],
    nextRoutes: ['ai-quality-engineer', 'qa-lead-manager'],
  },
  {
    id: 'fresh-graduate',
    title: 'Fresh Graduate → First QA Job',
    subtitle: 'Zero to employed in 3–4 months on a minimal budget',
    icon: '🎓',
    color: '#14b8a6',
    targetRole: 'Junior QA Engineer / QA Analyst',
    salaryRange: '$55–75k (US) | ₹3–6 LPA (India) | £28–42k (UK)',
    totalCost: '$180–$350',
    totalCostUSD: 265,
    totalTime: '3–5 months',
    difficulty: 'Beginner',
    countriesHighDemand: ['🇮🇳 India', '🇵🇰 Pakistan', '🇵🇱 Poland', '🇿🇦 South Africa', '🇦🇺 Australia', '🇬🇧 UK'],
    prerequisites: ['Basic computer literacy', 'Interest in software quality', 'Any technical or non-technical degree'],
    summary: 'The fastest and cheapest path to your first QA job. ISTQB Foundation gives you the credential, QA Academy 2.0 gives you the skills (free), and Postman API cert adds practical proof. Budget-friendly: total cost under $350 and most of the learning is free. This platform IS your study material.',
    steps: [
      {
        certId: 'qa-academy-2',
        certName: 'QA Academy 2.0 — Modules 1–7 (Free)',
        why: 'Complete the first 7 modules of this platform: Testing Fundamentals, SDLC, Test Design, API Testing, Agile, and Defect Management. Build your portfolio with the practice labs and capstone projects. Free and immediately applicable.',
        duration: '4–6 weeks',
        cost: '$0 (Free)',
        costUSD: 0,
        skillsGained: ['Manual testing fundamentals', 'Test case writing', 'Bug reporting', 'Agile testing', 'API testing basics'],
        unlocks: ['ISTQB exam readiness', 'Portfolio projects', 'Interview confidence'],
        icon: '🧪',
      },
      {
        certId: 'istqb-ctfl',
        certName: 'ISTQB Foundation Level (CTFL)',
        why: 'Your first paid certification. Recognised in 120+ countries. Even at junior level, ISTQB significantly increases interview callback rates. In India, UK, Europe and UAE it\'s often required for entry-level roles.',
        duration: '4–6 weeks',
        cost: '$180–$250',
        costUSD: 215,
        skillsGained: ['Testing principles', 'Test design techniques', 'Static testing', 'Test management basics', 'Tool terminology'],
        unlocks: ['Junior QA Engineer roles globally', 'Interview shortlisting', 'Freelance testing work'],
        icon: '📋',
      },
      {
        certId: 'postman-expert',
        certName: 'Postman API Fundamentals Certification',
        why: 'Free, practical, and takes only 1–2 weeks. API testing skill separates you from 80% of fresh graduates. Postman badge on LinkedIn gets recruiter attention.',
        duration: '1–2 weeks',
        cost: '$0 (Free)',
        costUSD: 0,
        skillsGained: ['REST API concepts', 'Postman collections', 'API test automation', 'Environment setup', 'Mock servers'],
        unlocks: ['API testing roles', 'Backend QA projects', 'Higher starting salary'],
        icon: '📬',
      },
    ],
    nextRoutes: ['junior-to-senior', 'manual-to-automation'],
  },
];
