/* QA Academy — Khirad chatbot knowledge base */

export interface KBEntry {
  id: string;
  patterns: string[];
  answer: string;
  topic: string;
  followUps?: string[];
}

// Helper so we can write multi-line answers cleanly without template-literal backtick collisions
function a(...lines: string[]): string { return lines.join('\n'); }

export const knowledgeBase: KBEntry[] = [

  // ── Greetings ────────────────────────────────────────────────
  {
    id: 'greet-hello',
    patterns: ['hello', 'hi', 'hey', 'good morning', 'good afternoon', 'good evening', 'sup', 'howdy'],
    topic: 'General',
    answer: a(
      "Hello! 👋 I'm **Khirad**, your QA Academy assistant. I'm here to help you navigate everything on this platform — learning paths, certifications, capstone projects, career guidance, and more.",
      '',
      'What would you like to explore today?'
    ),
    followUps: ['What can I learn here?', 'How do I get certified?', 'Which career path suits me?', 'Show me the capstone projects'],
  },
  {
    id: 'greet-how-are-you',
    patterns: ['how are you', 'how r u', 'you okay', 'you good', 'how do you feel'],
    topic: 'General',
    answer: a(
      "I'm doing great and ready to help you level up your QA skills! 🚀",
      '',
      "I have full knowledge of everything on QA Academy — from automation tools and CI/CD pipelines to career paths and certification prep. Ask me anything!"
    ),
    followUps: ['What topics are covered here?', 'How do I start learning?', 'What certifications are available?'],
  },
  {
    id: 'greet-name',
    patterns: ['what is your name', 'who are you', 'what are you', 'your name', 'tell me about yourself', 'introduce yourself'],
    topic: 'General',
    answer: a(
      "I'm **Khirad** — the QA Academy AI assistant. 🤖",
      '',
      "I'm trained on the complete QA Academy curriculum, including:",
      '• Every learning module and quiz',
      '• All certification tracks',
      '• Capstone project details',
      '• Career intelligence and salary data',
      '• Automation tools (Playwright, Cypress, Selenium, k6 and more)',
      '• CI/CD and GitHub Actions guides',
      '• AI tools for QA engineers',
      '',
      "I'm here to answer your questions, guide your learning journey, and help you build a successful QA career."
    ),
    followUps: ['What can you help me with?', 'Show me the learning path', 'Tell me about certifications'],
  },

  // ── Platform Overview ─────────────────────────────────────────
  {
    id: 'platform-overview',
    patterns: ['what is qa academy', 'what is this platform', 'what can i learn', 'what does this app do', 'overview', 'tell me about this platform', 'about this app'],
    topic: 'Platform',
    answer: a(
      '**QA Academy** is an AI-powered software testing education platform designed to take you from beginner to professional QA engineer. 🎓',
      '',
      "Here's everything you get:",
      '',
      '**📚 Learning Path** — Structured modules from fundamentals to advanced automation',
      '**🎯 Quiz Center** — Practice questions covering all QA topics',
      '**🤖 AI Tutor** — Ask any QA question and get expert answers',
      '**🏆 Capstone Projects** — Realistic workspaces with real hidden bugs to find',
      '**🏅 Certifications** — Earn recognised QA certificates',
      '**💼 Interview Prep** — 200+ real interview questions with answers',
      '**📊 Career Intelligence** — Salary data, career paths, and market trends',
      '**🔄 CI/CD & GitHub** — Learn pipeline automation for QA',
      '**🛠️ AI Tools** — Claude Code, Copilot, Cursor — all with install guides',
      '**🧪 Automation Tools** — Playwright, Cypress, Selenium, k6, Appium',
      '**📖 Glossary** — 100 QA terms with examples'
    ),
    followUps: ['How do I start?', 'What are capstone projects?', 'Which certifications are available?', 'Tell me about the quiz center'],
  },
  {
    id: 'platform-get-started',
    patterns: ['how do i start', 'where do i begin', 'getting started', 'how to start', 'first step', 'new here', 'beginner', 'just joined', 'just started'],
    topic: 'Platform',
    answer: a(
      "Welcome! Here's the fastest path to getting started on QA Academy: 🚀",
      '',
      '**Step 1 — Visit Learning Path** 📚',
      'Go to Learning Path in the sidebar. Start with "QA Fundamentals" — it covers the STLC, test types, and bug lifecycle. Should take 2–3 hours.',
      '',
      '**Step 2 — Test your knowledge** 🎯',
      'After each module, head to the Quiz Center and take the matching quiz. This locks in what you learned.',
      '',
      '**Step 3 — Get your first certification** 🏅',
      "Once you've completed 3 modules, you're eligible for the QA Fundamentals certificate. It's free on the Basic plan.",
      '',
      '**Step 4 — Pick a specialisation** 🔀',
      'Visit Career Intelligence → Career Quiz to find which QA path matches your interests and skills.',
      '',
      '**Step 5 — Do a Capstone Project** 🏆',
      "These are the best way to build real experience. Start with Project 1 (E-commerce Platform) — it has realistic hidden bugs to find.",
      '',
      'Any specific area you want to dive into first?'
    ),
    followUps: ['Tell me about the learning path modules', 'What is the career quiz?', 'Show me capstone projects', 'How do certifications work?'],
  },

  // ── Learning Path ─────────────────────────────────────────────
  {
    id: 'learning-path-overview',
    patterns: ['learning path', 'modules', 'curriculum', 'what can i study', 'courses', 'what modules', 'study plan', 'learning plan'],
    topic: 'Learning Path',
    answer: a(
      'The **Learning Path** is your structured curriculum — 21 modules organised into 5 levels: 🎓',
      '',
      '**🌱 Beginner**',
      '• QA Fundamentals & STLC',
      '• Test Case Design Techniques',
      '• Bug Reporting & Defect Lifecycle',
      '• Agile Testing & Scrum',
      '',
      '**🌿 Intermediate**',
      '• Web Application Testing',
      '• REST API Testing',
      '• Database Testing (SQL basics)',
      '• Test Management Tools (Jira, TestRail)',
      '',
      '**⚡ Advanced**',
      '• Playwright E2E Automation',
      '• Selenium WebDriver',
      '• CI/CD for QA Engineers',
      '• Performance Testing with k6',
      '',
      '**🔥 Expert**',
      '• SDET Skills & Framework Design',
      '• Security Testing (OWASP)',
      '• Mobile Testing with Appium',
      '• AI & ML Testing',
      '',
      '**👑 QA Lead**',
      '• Test Strategy & Planning',
      '• Team Leadership & Mentoring',
      '• Quality Metrics & Reporting',
      '• Risk-Based Testing',
      '',
      'Each module earns you XP and contributes to certification eligibility.'
    ),
    followUps: ['How long does each module take?', 'How do I earn XP?', 'Tell me about certifications', 'Which module should I start with?'],
  },
  {
    id: 'learning-xp',
    patterns: ['xp', 'experience points', 'how to earn xp', 'points', 'level up', 'how do i level', 'progression', 'badges'],
    topic: 'Learning Path',
    answer: a(
      '**XP (Experience Points)** is how you track progress and level up on QA Academy. Here\'s how to earn it: ⭐',
      '',
      '**Earning XP:**',
      '• Complete a module → 50–200 XP depending on difficulty',
      '• Pass a quiz (80%+ score) → 30–100 XP',
      '• Complete a daily challenge → 20–50 XP',
      '• Finish a capstone project → 300–500 XP',
      '• Earn a certification → 500 XP',
      '',
      '**Levels (based on total XP):**',
      '• 🌱 Beginner — 0 XP',
      '• 🌿 Intermediate — 500 XP',
      '• ⚡ Advanced — 1,500 XP',
      '• 🔥 Expert — 3,000 XP',
      '• 👑 QA Lead — 5,000 XP',
      '• 🎯 QA Manager — 8,000 XP',
      '• 🤖 AI Quality Eng — 12,000 XP',
      '',
      "Your current level and XP are always visible in the sidebar. Check the Dashboard for today's challenge — it's the fastest daily XP source!"
    ),
    followUps: ["What are daily challenges?", 'Tell me about certifications', 'What is the dashboard?'],
  },

  // ── Quiz Center ───────────────────────────────────────────────
  {
    id: 'quiz-center',
    patterns: ['quiz', 'quizzes', 'quiz center', 'test my knowledge', 'practice questions', 'exam', 'mock test'],
    topic: 'Quiz Center',
    answer: a(
      'The **Quiz Center** is where you test your knowledge across every QA topic. 🎯',
      '',
      '**What\'s inside:**',
      '• 500+ questions across all QA domains',
      '• Multiple-choice and scenario-based questions',
      '• Immediate feedback with explanations for every answer',
      '• Difficulty levels: Beginner, Intermediate, Advanced, Expert',
      '• Topic filters: Automation, API Testing, Performance, Security, Mobile, Agile, and more',
      '',
      '**Quiz modes:**',
      '• **Practice Mode** — No time limit, see explanations as you go',
      '• **Exam Mode** — Timed, simulates real certification exams',
      '• **Weak Areas** — Focuses only on topics you\'ve answered incorrectly',
      '',
      '**Scoring:**',
      '• 80%+ → Pass + full XP reward',
      '• 60–79% → Partial XP, flagged for review',
      '• Below 60% → Retry recommended, no XP deducted',
      '',
      'Quiz results feed into your profile and help identify which modules to focus on next.'
    ),
    followUps: ['How do I access the quiz center?', 'What topics are covered?', 'Does quiz performance affect certification?'],
  },

  // ── Certifications ────────────────────────────────────────────
  {
    id: 'certifications-overview',
    patterns: ['certification', 'certificates', 'cert', 'certs', 'how to get certified', 'earn certificate', 'badge', 'diploma'],
    topic: 'Certifications',
    answer: a(
      '**QA Academy Certifications** are industry-recognised credentials you earn by completing modules and passing assessments. 🏅',
      '',
      '**Available Certifications:**',
      '',
      '🥉 **QA Fundamentals** — Complete beginner modules + pass the fundamentals exam',
      '🥈 **Web Automation Engineer** — Master Playwright or Selenium + practical assessment',
      '🥈 **API Testing Specialist** — REST API testing, Postman, and Newman',
      '🥇 **SDET Professional** — Full automation framework design + CI/CD integration',
      '🥇 **Performance Testing Engineer** — k6 load testing + Grafana analysis',
      '🏆 **AI Quality Engineer** — LLM evaluation, bias detection, AI testing frameworks',
      '🏆 **Security QA Specialist** — OWASP Top 10, Burp Suite, penetration testing basics',
      '🌟 **QA Lead Certification** — Strategy, team management, and metrics',
      '',
      '**How to earn them:**',
      '1. Complete the required learning modules',
      '2. Score 80%+ on the certification exam',
      '3. Download your certificate (PDF + shareable link)',
      '4. Add to LinkedIn with one click',
      '',
      'Free plan includes 1 certificate. Pro and Enterprise unlock all certificates.'
    ),
    followUps: ['Which certificate should I get first?', 'Are these certificates recognised by employers?', 'Tell me about the pricing plans', 'How do I add to LinkedIn?'],
  },
  {
    id: 'cert-recognised',
    patterns: ['recognised', 'recognized', 'employer', 'worth it', 'value', 'legit', 'legitimate', 'accepted', 'industry standard', 'respected'],
    topic: 'Certifications',
    answer: a(
      "Great question. Here's an honest answer: 💬",
      '',
      '**QA Academy certificates** are portfolio credentials — they demonstrate practical skills through project-based evidence, similar to Udemy or Coursera certificates.',
      '',
      '**What employers actually value:**',
      '• The skills you demonstrate in interviews (not just the certificate)',
      '• Your GitHub portfolio showing real automation code',
      '• Capstone projects you\'ve completed with measurable results',
      '• Contributions to open-source test projects',
      '',
      '**Industry certifications that carry weight:**',
      '• **ISTQB Foundation** — the most globally recognised QA cert ($200–300)',
      '• **AWS Certified DevOps Engineer** — if you do QAOps',
      '• **Certified Ethical Hacker (CEH)** — for security QA',
      '',
      '**Best approach:** Use QA Academy certificates + the skills you build here to pass ISTQB or a company\'s technical interview. The certificate says "I studied this." Your capstone project and GitHub say "I can actually do this." Employers care about both.'
    ),
    followUps: ['Tell me about ISTQB', 'What are capstone projects?', 'How do I build a QA portfolio?'],
  },

  // ── Capstone Projects ─────────────────────────────────────────
  {
    id: 'capstone-overview',
    patterns: ['capstone', 'capstone project', 'projects', 'workspace', 'real project', 'practice project', 'hands on', 'hands-on', 'practical'],
    topic: 'Capstone Projects',
    answer: a(
      '**Capstone Projects** are the most realistic feature on QA Academy — they let you test actual simulated applications with real hidden bugs. 🏆',
      '',
      '**How they work:**',
      '1. Select a project and click "🧪 Launch Workspace"',
      '2. Read the project brief and acceptance criteria',
      '3. Explore the live simulated app in the Test App tab',
      '4. Find hidden bugs by interacting with the app',
      '5. File bug reports in the Jira-style Bug Tracker',
      '6. Check test cases off as you execute them',
      '7. View your score in the Report tab',
      '',
      '**Available workspaces:**',
      '',
      '🛒 **Project 1: E-Commerce Platform** (Beginner)',
      '→ ShopNow store with 6 hidden bugs: empty cart checkout, negative quantity, tax calculation error, invalid promo codes, email validation bypass, and more',
      '',
      '🤖 **Project 2: AI Chatbot Testing** (Intermediate)',
      '→ "Khirad" customer service chatbot with 6 AI quality failures: prompt injection, jailbreak, hallucination, inconsistent answers, medical advice, and inappropriate apologies',
      '',
      '🏢 **Project 5: SaaS Application** (Advanced)',
      '→ CRM app with 6 security/access control bugs: tenant data leak, missing auth on DELETE, manager billing access, missing delete confirmation, silent audit log failure, and silent viewer edit failure',
      '',
      '**Scoring:** 60% from bugs found + 40% from test cases executed'
    ),
    followUps: ['How do I find hidden bugs?', 'What is the E-commerce capstone?', 'Tell me about the AI chatbot project', 'How is the score calculated?'],
  },
  {
    id: 'capstone-ecommerce',
    patterns: ['ecommerce', 'e-commerce', 'shopnow', 'shop', 'cart', 'checkout', 'promo', 'project 1'],
    topic: 'Capstone Projects',
    answer: a(
      '**Project 1: E-Commerce Platform (ShopNow)** 🛒',
      '',
      'This is a simulated online shop with 6 deliberately planted bugs. Here are hints for finding them:',
      '',
      '**Areas to test:**',
      '• The shopping cart — try edge cases with quantities',
      '• The promo code field — what happens with invalid codes?',
      '• The checkout flow — what if certain fields are not valid?',
      '• The tax display — does the displayed rate match the calculated amount?',
      '• The checkout button — what happens when the cart is empty?',
      '',
      '**Suggested test cases to run:**',
      '1. Add item, proceed to checkout — happy path',
      '2. Try to checkout with an empty cart',
      '3. Set quantity to 0 or negative',
      '4. Set quantity to a very large number (try 100+)',
      '5. Enter an invalid promo code',
      '6. Enter an invalid email at checkout',
      '7. Compare the displayed tax rate to the actual tax charged',
      '',
      '**Score target:** Find all 6 bugs + complete all 8 test cases = 100%'
    ),
    followUps: ['How do I file a bug report?', 'Tell me about the AI chatbot project', 'Tell me about the SaaS project'],
  },
  {
    id: 'capstone-chatbot',
    patterns: ['chatbot project', 'ai chatbot', 'llm testing', 'ai testing project', 'project 2', 'chatbot bugs'],
    topic: 'Capstone Projects',
    answer: a(
      '**Project 2: AI Chatbot Testing** 🤖',
      '',
      'This project simulates testing an AI customer service chatbot for a retail company. It teaches you how to evaluate AI quality — a fast-growing skill.',
      '',
      '**The 6 AI quality failures to find:**',
      '1. **System prompt exposure** — Can you make the chatbot reveal its instructions?',
      '2. **Jailbreak vulnerability** — Can you bypass its content restrictions with role-play?',
      '3. **Hallucination** — Does it invent product details for non-existent items?',
      '4. **Inconsistent answers** — Does it give different answers to the same question?',
      '5. **Inappropriate advice** — Does it give medical advice it should not give?',
      '6. **Sycophantic behaviour** — How does it respond to abusive messages?',
      '',
      '**How to trigger them:**',
      'Use the Test Prompts panel on the left side — it has 7 pre-written prompts that each target a specific failure. You can also type your own messages.',
      '',
      '**Why this matters:** AI chatbot testing is one of the highest-demand QA skills in 2025. Companies building AI products desperately need testers who understand these failure modes.'
    ),
    followUps: ['What is AI quality testing?', 'Tell me about the SaaS project', 'Career paths in AI testing'],
  },
  {
    id: 'capstone-saas',
    patterns: ['saas', 'crm', 'project 5', 'tenant', 'role', 'access control', 'security project', 'admin', 'viewer'],
    topic: 'Capstone Projects',
    answer: a(
      '**Project 5: SaaS Application (Multi-Tenant CRM)** 🏢',
      '',
      'This is the most advanced capstone — a real enterprise SaaS CRM with role-based access control and multi-tenant data isolation. It tests security and access control bugs.',
      '',
      '**Test controls:**',
      'The Test Controls panel lets you switch between:',
      '• **Roles:** Admin / Manager / Viewer',
      '• **Tenants:** Acme Corp (A) / Globex Inc (B)',
      '',
      '**The 6 bugs to find:**',
      '1. **Tenant data leak** — Does Tenant B see Tenant A\'s data?',
      '2. **Missing auth on API** — Does a DELETE request with a Viewer token get blocked?',
      '3. **Manager billing access** — Should Managers access billing settings?',
      '4. **Missing delete confirmation** — Does Admin get a confirmation before deleting records?',
      '5. **Silent audit log failure** — Does the audit log record all actions?',
      '6. **Silent edit failure** — When a Viewer tries to edit, what happens?'
    ),
    followUps: ['What is role-based access control?', 'What are security test techniques?', 'How do I score 100% on capstones?'],
  },

  // ── Interview Prep ────────────────────────────────────────────
  {
    id: 'interview-prep',
    patterns: ['interview', 'interview prep', 'interview questions', 'job interview', 'prepare for interview', 'interview practice', 'technical interview'],
    topic: 'Interview Prep',
    answer: a(
      'The **Interview Prep** section has everything you need to land a QA role. 💼',
      '',
      '**What\'s inside:**',
      '• 200+ real interview questions with model answers',
      '• Questions organised by: Fundamentals, Automation, API, Performance, Security, Agile, Behavioural',
      '• Difficulty tags: Junior, Mid-Level, Senior, Lead',
      '• Company-specific question patterns (FAANG, startups, enterprise)',
      '',
      '**Most common QA interview topics:**',
      '• What is the STLC? (Software Testing Life Cycle)',
      '• Difference between smoke, sanity, regression, and exploratory testing',
      '• How do you prioritise test cases with limited time?',
      '• Write a Playwright/Selenium test for a login page (live coding)',
      '• How do you handle flaky tests in CI?',
      '• What is your approach to testing an API with no documentation?',
      '• Explain a time you found a critical bug late in the cycle',
      '',
      '**Interview Prep is found in the sidebar under 💼 Interview Prep.**',
      '',
      'Want me to answer any specific interview question right now? Just ask!'
    ),
    followUps: ['What is the STLC?', 'How do I test an API?', 'What are the most common QA interview questions?'],
  },
  {
    id: 'interview-stlc',
    patterns: ['stlc', 'software testing life cycle', 'sdlc', 'testing lifecycle', 'test life cycle'],
    topic: 'Interview Prep',
    answer: a(
      'The **STLC (Software Testing Life Cycle)** is one of the most common interview topics. Here\'s a complete answer: 📋',
      '',
      '**The 6 phases of STLC:**',
      '',
      '**1. Requirements Analysis**',
      'QA team reviews requirements, identifies testable items, and raises clarifications with BAs/developers.',
      '',
      '**2. Test Planning**',
      'Create the test plan: scope, approach, resources, schedule, risk assessment, entry/exit criteria.',
      '',
      '**3. Test Case Design**',
      'Write test cases using techniques: Equivalence Partitioning, Boundary Value Analysis, Decision Tables, State Transition.',
      '',
      '**4. Test Environment Setup**',
      'Configure test servers, databases, test data, tools, and access credentials.',
      '',
      '**5. Test Execution**',
      'Run test cases, log defects in Jira, track test progress against the plan.',
      '',
      '**6. Test Closure**',
      'Analyse test results, write the test summary report, archive test artifacts, capture lessons learned.',
      '',
      '**Interview tip:** Always mention exit criteria — "Testing is complete when all P1/P2 defects are fixed and the defect fix rate exceeds 95%." This shows maturity.'
    ),
    followUps: ['What is test planning?', 'What are test case design techniques?', 'What is the defect lifecycle?'],
  },
  {
    id: 'interview-flaky-tests',
    patterns: ['flaky test', 'flaky', 'intermittent', 'test failing randomly', 'unstable test', 'test passes sometimes', 'unreliable test'],
    topic: 'Interview Prep',
    answer: a(
      '**Flaky tests** are one of the most common interview topics for automation engineers. ⚡',
      '',
      '**What is a flaky test?**',
      'A test that passes and fails inconsistently without any code changes — making CI unreliable and eroding trust in the test suite.',
      '',
      '**Common causes:**',
      '• Race conditions (element not yet visible when assertion runs)',
      '• Shared test data (test A modifies data that test B depends on)',
      '• Time-dependent logic (tests that rely on the current date/time)',
      '• Network/API timeouts in CI environments',
      '• Order dependency (tests must run in a specific sequence)',
      '',
      '**How to fix them:**',
      '1. **Use smart waits** — page.waitForSelector() instead of sleep(1000)',
      '2. **Isolate test data** — each test creates and cleans up its own data',
      '3. **Add retries** — set retries: 2 in Playwright config for CI only',
      '4. **Quarantine** — move flaky tests to a separate suite so they do not block CI while you fix them',
      '5. **Root cause analysis** — add screenshots and traces on failure, reproduce locally',
      '',
      '**Interview tip:** Mention quarantining flaky tests AND fixing the root cause. Never just add retries without investigating.'
    ),
    followUps: ['How do I set up retries in Playwright?', 'What is test isolation?', 'How does CI/CD relate to testing?'],
  },

  // ── Career Intelligence ───────────────────────────────────────
  {
    id: 'career-overview',
    patterns: ['career', 'career path', 'career switch', 'career change', 'career advice', 'job', 'career intelligence', 'which career'],
    topic: 'Career',
    answer: a(
      'The **Career Intelligence** section is one of the most powerful features on QA Academy. 🚀',
      '',
      "Here's what it covers:",
      '',
      '**🎯 Career Quiz** — Answer 6 questions and discover which QA specialisation fits your personality, skills, and goals.',
      '',
      '**🗺️ Career Paths** — Detailed profiles of all 7 QA specialisations:',
      '• SDET ($85k–$160k) — writes automation frameworks',
      '• AI Quality Engineer ($110k–$200k) — tests AI/ML systems',
      '• Security QA ($100k–$180k) — penetration testing',
      '• Performance Engineer ($90k–$165k) — load and stress testing',
      '• QA Lead ($90k–$150k) — team leadership',
      '• Mobile QA ($80k–$145k) — iOS and Android',
      '• DevOps QA ($95k–$170k) — CI/CD quality pipelines',
      '',
      '**🔀 Career Switch Guide** — Step-by-step monthly plans for switching roles, with salary jump estimates',
      '',
      '**📈 Market Trends** — What skills are growing, what\'s declining, and what to do about it',
      '',
      '**💰 Salary Guide** — Full table by role and experience level + negotiation tips',
      '',
      '**⚠️ Risk Assessment** — Is your current role at risk of automation? Find out now.',
      '',
      'Visit **🚀 Career Intelligence** in the sidebar.'
    ),
    followUps: ['Which QA career pays the most?', 'How do I switch from manual to SDET?', 'Is manual QA at risk?', 'Tell me about the career quiz'],
  },
  {
    id: 'career-salary',
    patterns: ['salary', 'salary range', 'how much do qa earn', 'pay', 'compensation', 'wages', 'earn', 'income', 'money'],
    topic: 'Career',
    answer: a(
      "Here's a snapshot of QA salaries by specialisation (US market, 2025): 💰",
      '',
      '| Role | Junior | Senior | Lead |',
      '|---|---|---|---|',
      '| Manual QA | $45–65k | $80–110k | $100–130k |',
      '| SDET | $75–95k | $130–165k | $155–200k |',
      '| AI Quality Eng | $90–115k | $150–190k | $180–240k |',
      '| Security QA | $80–105k | $140–175k | $170–220k |',
      '| Performance Eng | $70–95k | $125–160k | $155–195k |',
      '| DevOps QA | $75–100k | $135–170k | $165–210k |',
      '| QA Lead | — | $115–155k | $145–200k |',
      '',
      '**Key insights:**',
      '• SDET earns 40–70% more than manual QA with the same years of experience',
      '• AI Quality Engineering is the fastest-growing AND highest-ceiling QA role',
      '• Security QA always pays a premium — every company needs it',
      '• Remote roles at US companies from other countries can 2–4x local rates',
      '',
      'Visit **Salary Guide** in Career Intelligence for the full breakdown + negotiation playbook.'
    ),
    followUps: ['How do I switch to SDET?', 'Tell me about AI Quality Engineering', 'What are salary negotiation tips?'],
  },
  {
    id: 'career-manual-risk',
    patterns: ['manual qa risk', 'is manual qa dying', 'manual testing future', 'will manual qa be automated', 'ai replacing qa', 'job security qa'],
    topic: 'Career',
    answer: a(
      'This is a critical question and deserves an honest answer. ⚠️',
      '',
      '**The reality:**',
      'Basic manual regression testing — clicking through checklists and executing scripted test cases — is genuinely at risk. AI tools like Testim, Playwright AI, and autonomous agents can increasingly do this work faster and cheaper.',
      '',
      '**What is NOT going away:**',
      '• Exploratory testing (creative, experience-based bug finding)',
      '• Test strategy and planning',
      '• Automation engineering (SDETs)',
      '• AI system testing (rapidly growing)',
      '• Security testing',
      '• Performance engineering',
      '• QA leadership',
      '',
      '**The timeline:**',
      '• Now–2026: Basic regression execution is shrinking',
      '• 2026–2028: Mid-level automation skills are the safe floor',
      '• 2028+: AI quality engineering, security, and strategy are premium',
      '',
      '**What to do:**',
      'If you\'re doing manual-only QA today, the Risk Assessment in Career Intelligence will give you a personalised action plan. The short version: start learning Playwright now. 3–6 months of focused effort can move you from at-risk to in-demand.',
      '',
      'Want me to suggest a specific learning path based on where you are now?'
    ),
    followUps: ['How do I learn Playwright?', 'Manual QA to SDET switch plan', 'What is the career risk assessment?'],
  },

  // ── CI/CD ─────────────────────────────────────────────────────
  {
    id: 'cicd-overview',
    patterns: ['ci cd', 'cicd', 'ci/cd', 'continuous integration', 'continuous deployment', 'continuous delivery', 'pipeline', 'github actions', 'jenkins', 'devops'],
    topic: 'CI/CD',
    answer: a(
      'The **CI/CD & GitHub Actions** section covers everything about automating QA into software delivery pipelines. 🔄',
      '',
      '**What CI/CD means:**',
      '• **CI (Continuous Integration)** — Every code push automatically runs: build → lint → unit tests → integration tests. Catches bugs before they reach staging.',
      '• **Continuous Delivery** — Every passing build is packaged and ready to deploy at any time.',
      '• **Continuous Deployment** — Every passing build automatically goes to production (no human gate).',
      '',
      '**What the CI/CD section covers:**',
      '• GitHub Actions workflow YAML — from scratch to production-grade',
      '• Running Playwright tests in CI with parallel sharding',
      '• API tests with Postman/Newman in CI',
      '• k6 performance tests with CI thresholds',
      '• Complete 8-stage QA pipeline (lint → unit → API → E2E → security → staging deploy)',
      '• Docker-based test environments',
      '• Secrets management and branch protection rules',
      '',
      '**Why it matters for interviews:**',
      'Being able to say "I set up a GitHub Actions pipeline that runs Playwright tests in parallel across 4 shards and blocks PRs from merging on failure" immediately separates you from QAs who only run tests locally.',
      '',
      'Find it in the sidebar: **🔄 CI/CD & GitHub**'
    ),
    followUps: ['How do I run Playwright in CI?', 'What are branch protection rules?', 'Tell me about GitHub Actions triggers'],
  },

  // ── Automation Tools ──────────────────────────────────────────
  {
    id: 'playwright-info',
    patterns: ['playwright', 'playwright test', 'microsoft playwright', 'e2e test', 'end to end', 'browser test'],
    topic: 'Automation Tools',
    answer: a(
      '**Playwright** is the recommended E2E testing tool on QA Academy — and the most in-demand automation skill in the job market right now. 🎭',
      '',
      '**Why Playwright:**',
      '• Runs Chromium, Firefox, and WebKit (Safari engine) — true cross-browser',
      '• Built-in auto-waiting — no manual sleep() calls needed',
      '• Faster and more reliable than Selenium',
      '• Native TypeScript support',
      '• Built-in API testing, component testing, and mobile emulation',
      '• Free, open-source, backed by Microsoft',
      '',
      '**Install in 30 seconds:**',
      'Run: npm init playwright@latest',
      'The wizard installs everything including browsers.',
      '',
      '**Key selectors:**',
      "• page.getByRole('button', { name: 'Submit' }) — role-based (most resilient)",
      "• page.getByLabel('Email') — label-based",
      "• page.getByTestId('login-btn') — data-testid attribute",
      '',
      '**Run tests:**',
      'npx playwright test → run all tests',
      'npx playwright test --ui → visual UI mode',
      'npx playwright codegen → record tests by clicking',
      '',
      'The full installation guide is in **🧪 Automation Tools → Playwright** in the sidebar.'
    ),
    followUps: ['How do I install Playwright?', 'Playwright vs Cypress — which should I learn?', 'How do I run Playwright in CI?'],
  },
  {
    id: 'playwright-vs-cypress',
    patterns: ['playwright vs cypress', 'cypress vs playwright', 'which is better playwright cypress', 'should i learn playwright or cypress', 'playwright or cypress'],
    topic: 'Automation Tools',
    answer: a(
      '**Playwright vs Cypress — the real comparison:** 🎭 vs 🌲',
      '',
      '**Playwright wins on:**',
      '• Cross-browser: Chromium + Firefox + WebKit (Cypress only does Chrome/Edge/Firefox)',
      '• Speed: Playwright is ~2x faster due to CDP protocol (vs Cypress in-browser)',
      '• Multi-tab/multi-window support (Cypress does not support this)',
      '• API testing built-in (request fixture)',
      '• Parallel sharding out of the box — no paid plan needed',
      '• Language support: TypeScript, Python, Java, C# (Cypress is JS/TS only)',
      '',
      '**Cypress wins on:**',
      '• DX (Developer Experience) — the time-travel debugger is incredible',
      '• Component testing — tighter React/Vue integration',
      '• Easier for frontend-focused developers to start',
      '• Real-time browser preview during test runs',
      '',
      '**The verdict:**',
      '• **Learning for a job?** → Learn Playwright. More job postings, faster, works in any language.',
      '• **Frontend developer?** → Cypress for component tests is excellent.',
      '• **Both?** → Learn Playwright first (3–4 weeks), then Cypress is easy to pick up (1 week).',
      '',
      'QA Academy covers both in full detail in **🧪 Automation Tools**.'
    ),
    followUps: ['How do I install Playwright?', 'How do I install Cypress?', 'Tell me about Selenium'],
  },
  {
    id: 'selenium-info',
    patterns: ['selenium', 'selenium webdriver', 'webdriver', 'selenium grid'],
    topic: 'Automation Tools',
    answer: a(
      '**Selenium** is the industry standard for browser automation — still widely used in enterprise environments. 🤖',
      '',
      '**Why you should know it:**',
      '• Huge job market — most enterprise QA job listings still mention Selenium',
      '• Supports Java, Python, C#, JavaScript, Ruby — works with any tech stack',
      '• Selenium Grid enables massive parallel test execution',
      '• WebDriver is a W3C standard — knowledge transfers to Appium (mobile)',
      '',
      '**When to choose Selenium over Playwright:**',
      '• Your team uses Java exclusively',
      '• You\'re maintaining an existing Selenium suite',
      '• You need maximum browser/OS coverage via Selenium Grid',
      '',
      '**Selenium 4 improvements:**',
      '• Auto-manages ChromeDriver (no more version mismatch issues)',
      '• CDP protocol support (similar to Playwright)',
      '• Relative locators and improved Grid architecture',
      '',
      '**Quick install (Python):**',
      'pip install selenium',
      '',
      'Full guide in **🧪 Automation Tools → Selenium**.'
    ),
    followUps: ['Playwright vs Selenium which is better?', 'How do I set up Selenium Grid?', 'Tell me about Appium'],
  },
  {
    id: 'k6-info',
    patterns: ['k6', 'load testing', 'performance testing', 'stress test', 'load test', 'performance test', 'jmeter', 'gatling', 'vus', 'virtual users'],
    topic: 'Automation Tools',
    answer: a(
      '**k6** is the recommended performance testing tool on QA Academy and the most developer-friendly load tester available. 📊',
      '',
      '**What k6 does:**',
      'Simulates thousands of virtual users hitting your application simultaneously to find:',
      '• How fast the app responds under load (P95 response time)',
      '• At what point it starts failing (error rate)',
      '• Maximum concurrent users before degradation',
      '• Which specific endpoints are the bottleneck',
      '',
      '**Why k6 over JMeter:**',
      '• Write tests in JavaScript (not XML GUIs)',
      '• CLI-first — perfect for CI/CD integration',
      '• Threshold-based pass/fail (CI-friendly exit codes)',
      '• Grafana integration for real-time dashboards',
      '• Built by Grafana Labs (enterprise backing)',
      '',
      '**Install:**',
      'brew install k6          ← macOS',
      'winget install k6        ← Windows',
      '',
      '**Quick test (JavaScript):**',
      "import http from 'k6/http';",
      "export const options = { vus: 50, duration: '30s' };",
      "export default function() { http.get('https://yourapp.com'); }",
      '',
      '**Key thresholds:**',
      "http_req_duration: p(95) < 500ms  ← 95% under 500ms",
      "http_req_failed: rate < 1%         ← error rate below 1%",
      '',
      'Full guide in **🧪 Automation Tools → k6 Load Testing**.'
    ),
    followUps: ['How do I run k6 in CI?', 'What is P95 response time?', 'Tell me about Grafana dashboards'],
  },
  {
    id: 'appium-info',
    patterns: ['appium', 'mobile testing', 'mobile automation', 'ios testing', 'android testing', 'mobile app', 'xcuitest', 'espresso', 'webdriverio'],
    topic: 'Automation Tools',
    answer: a(
      '**Appium** is the standard for automating iOS and Android native app testing. 📱',
      '',
      '**How Appium works:**',
      "Appium is an HTTP server that wraps Apple's XCUITest (iOS) and Google's UiAutomator2 (Android) behind the standard WebDriver protocol. Your test code is the same for both platforms.",
      '',
      '**What you can automate:**',
      '• Native apps (built with Swift/Kotlin/Java)',
      '• Hybrid apps (React Native, Ionic, Cordova)',
      '• Mobile web apps (Chrome/Safari on mobile)',
      '',
      '**Prerequisites:**',
      '• **Android:** Android Studio + JDK 11+ + set ANDROID_HOME',
      "• **iOS:** Xcode + macOS only (Apple's restriction)",
      '• Node.js 18+ for Appium server',
      '',
      '**Quick install:**',
      'npm install -g appium',
      'appium driver install uiautomator2  ← Android',
      'appium driver install xcuitest      ← iOS (macOS only)',
      'npm install -g @appium/doctor       ← verify setup',
      '',
      'Full installation guide in **🧪 Automation Tools → Appium (Mobile)**.'
    ),
    followUps: ['How do I set up Android for Appium?', 'Tell me about iOS testing', 'What is BrowserStack?'],
  },

  // ── AI Tools ──────────────────────────────────────────────────
  {
    id: 'ai-tools-overview',
    patterns: ['ai tools', 'ai coding', 'claude code', 'github copilot', 'cursor', 'codeium', 'tabnine', 'ai for qa', 'ai coding tool', 'ide ai'],
    topic: 'AI Tools',
    answer: a(
      'The **AI Tools & IDEs** section covers every major AI coding assistant and how to use them for QA work. 🛠️',
      '',
      '**The main tools covered:**',
      '',
      '🤖 **Claude Code** (Anthropic) — CLI + VS Code/JetBrains extension. Best for writing complete test suites, debugging CI failures, and codebase-wide refactors.',
      '',
      '✈️ **GitHub Copilot** (Microsoft) — Most popular, free tier available, great for autocomplete and PR reviews. Works in VS Code, JetBrains, Vim.',
      '',
      '🖱️ **Cursor** — Full VS Code fork with multi-file AI edits. Best IDE experience. 2,000 free completions/month.',
      '',
      '⚡ **Codeium / Windsurf** — Free unlimited completions. Best free Copilot alternative. Windsurf IDE has an autonomous "Cascade" agent.',
      '',
      '🔵 **Tabnine** — Privacy-first, can run locally (no data sent to cloud). Best for regulated industries.',
      '',
      '💻 **CLI tools:** Aider (terminal pair programmer), Ollama (100% local LLMs), llm CLI',
      '',
      '**For QA engineers specifically:**',
      'All these tools can write Playwright tests, debug CI failures, generate test data, and review test coverage — saving 3–5 hours per week.',
      '',
      'Find installation guides in **🛠️ AI Tools & IDEs**.'
    ),
    followUps: ['How do I install Claude Code?', 'How do I use Copilot for writing tests?', 'What is Cursor?'],
  },
  {
    id: 'claude-code-install',
    patterns: ['install claude code', 'claude code install', 'how to install claude', 'claude cli', 'anthropic cli'],
    topic: 'AI Tools',
    answer: a(
      '**Installing Claude Code** takes about 2 minutes: 🤖',
      '',
      '**Prerequisites:** Node.js 18+',
      '',
      '**Step 1 — Install (run in your terminal):**',
      'npm install -g @anthropic-ai/claude-code',
      '',
      '**Step 2 — Authenticate:**',
      'Run: claude',
      'This opens your browser to authenticate with your Anthropic account.',
      '',
      '**Step 3 — Use it in your project:**',
      'cd my-test-project && claude',
      'Then type in natural language:',
      '  "Write Playwright tests for the login page"',
      '  "This test is failing in CI: [paste error]. Fix it."',
      '  "Generate 20 realistic test users for this schema"',
      '',
      '**VS Code extension:**',
      'code --install-extension anthropic.claude-code',
      '',
      '**JetBrains plugin:**',
      'Settings → Plugins → Marketplace → Search "Claude Code"',
      '',
      'The full guide with screenshots is in **🛠️ AI Tools & IDEs → Claude Code**.'
    ),
    followUps: ['What can I do with Claude Code for QA?', 'Tell me about GitHub Copilot', 'Tell me about Cursor IDE'],
  },

  // ── Glossary ──────────────────────────────────────────────────
  {
    id: 'glossary',
    patterns: ['glossary', 'terms', 'definitions', 'terminology', 'what is regression', 'what is smoke test', 'what is sanity', 'what is exploratory', 'qa terms'],
    topic: 'Glossary',
    answer: a(
      'The **Glossary** has 100 QA terms with definitions and real-world examples — searchable by keyword and browsable A–Z. 📖',
      '',
      'Here are some of the most commonly asked-about terms:',
      '',
      '**Smoke Testing** — A quick, high-level check of the most critical features after a build to verify the app is stable enough for deeper testing.',
      '',
      '**Sanity Testing** — A narrow, targeted check of a specific area after a bug fix.',
      '',
      '**Regression Testing** — Re-running existing tests after changes to ensure nothing that used to work is now broken.',
      '',
      '**Exploratory Testing** — Unscripted, experience-based testing where the tester simultaneously designs and executes tests.',
      '',
      '**Shift-Left Testing** — Moving testing activities earlier in the development cycle — catching bugs when they\'re cheapest to fix.',
      '',
      '**Test Coverage** — The percentage of the codebase, features, or requirements that are covered by tests.',
      '',
      'Visit **📖 Glossary** in the sidebar to search all 100 terms.'
    ),
    followUps: ['What is the difference between smoke and sanity testing?', 'What is exploratory testing?', 'Explain test coverage'],
  },

  // ── Plans & Pricing ───────────────────────────────────────────
  {
    id: 'pricing',
    patterns: ['pricing', 'plans', 'price', 'cost', 'subscription', 'free plan', 'pro plan', 'enterprise', 'how much', 'upgrade'],
    topic: 'Pricing',
    answer: a(
      'QA Academy has three plans: 💎',
      '',
      '**🆓 Basic (Free)**',
      '• All learning modules — no paywall on content',
      '• Quiz Center with full access',
      '• 1 free certification (QA Fundamentals)',
      '• 3 capstone project workspaces',
      '• AI Tutor (10 messages/day)',
      '• Community support',
      '',
      '**⭐ Pro ($29/month)**',
      '• Everything in Basic',
      '• Unlimited certifications (all 8)',
      '• Unlimited AI Tutor messages',
      '• All capstone projects (including advanced)',
      '• Interview Prep full access (200+ questions)',
      '• Priority email support + LinkedIn certificate sharing',
      '',
      '**🏢 Enterprise ($99/user/month)**',
      '• Everything in Pro',
      '• Team admin dashboard and custom learning paths',
      '• Progress tracking for managers',
      '• Dedicated success manager, custom branding, SSO',
      '',
      '**Good news:** All learning content is free. You only need Pro for certifications, unlimited AI Tutor, and the full interview prep library.',
      '',
      'Visit **💎 Plans & Pricing** in the sidebar.'
    ),
    followUps: ['Which plan should I get?', 'Is the free plan enough to learn?', 'How do certifications work?'],
  },

  // ── QA Fundamentals ───────────────────────────────────────────
  {
    id: 'test-types',
    patterns: ['types of testing', 'what types of test', 'different testing types', 'kinds of testing', 'unit test', 'integration test', 'acceptance test'],
    topic: 'QA Fundamentals',
    answer: a(
      'Here are the main types of software testing: 🧪',
      '',
      '**By scope (testing pyramid):**',
      '• **Unit Tests** — Test individual functions in isolation. Fast, cheap, run in milliseconds. Should be 70% of your tests.',
      '• **Integration Tests** — Test how components work together (API calls, database queries). Medium speed.',
      '• **E2E (End-to-End) Tests** — Test complete user journeys through the real UI. Slowest but highest confidence.',
      '',
      '**By purpose:**',
      '• **Functional Testing** — Does the feature do what it\'s supposed to?',
      '• **Regression Testing** — Does the new change break anything that worked before?',
      '• **Performance Testing** — Does the app handle the expected load?',
      '• **Security Testing** — Are there vulnerabilities attackers could exploit?',
      '• **Usability Testing** — Can real users complete tasks easily?',
      '• **Accessibility Testing** — Does it work for users with disabilities?',
      '',
      '**By approach:**',
      '• **Smoke Testing** — Quick sanity check of critical paths after a deployment',
      '• **Exploratory Testing** — Unscripted, curiosity-driven testing',
      '• **Boundary Value Analysis** — Testing at the edges of valid ranges',
      '• **Equivalence Partitioning** — Grouping inputs into categories and testing one from each',
      '',
      'All of these are covered in depth in the Learning Path modules.'
    ),
    followUps: ['What is the testing pyramid?', 'How do I write unit tests?', 'Tell me about regression testing'],
  },
  {
    id: 'bug-lifecycle',
    patterns: ['bug lifecycle', 'defect lifecycle', 'defect life cycle', 'bug states', 'bug status', 'defect status', 'jira bug'],
    topic: 'QA Fundamentals',
    answer: a(
      'The **Defect Lifecycle** defines the states a bug travels through from discovery to closure: 🐛',
      '',
      '**States:**',
      '1. **New** — Bug reported by tester, not yet reviewed',
      '2. **Assigned** — Bug assigned to a developer for investigation',
      '3. **Open** — Developer has accepted the bug and is working on a fix',
      '4. **Fixed** — Developer has made the fix and passed it back for verification',
      '5. **Retest** — QA is re-testing the fixed functionality',
      '6. **Verified** — QA confirms the fix works correctly',
      '7. **Closed** — Bug is confirmed fixed and closed',
      '8. **Reopened** — Fix did not work or bug re-appeared — goes back to Open',
      '',
      '**Additional states:**',
      '• **Duplicate** — Same bug already reported',
      '• **Deferred** — Valid bug but will not be fixed in this release',
      '• **Rejected** — Not a bug (works as designed, or cannot reproduce)',
      '',
      '**Interview tip:** When a developer says "Not a Bug", go back to the requirements and present evidence. If it\'s genuinely ambiguous, escalate to the BA or PM rather than arguing with the developer.'
    ),
    followUps: ['How do I write a good bug report?', 'What is the STLC?', 'Tell me about Jira'],
  },
  {
    id: 'good-bug-report',
    patterns: ['bug report', 'how to write a bug report', 'defect report', 'good bug', 'report a bug', 'jira ticket'],
    topic: 'QA Fundamentals',
    answer: a(
      'A great bug report gets fixed faster. Here\'s the template: 📝',
      '',
      '**Title:** [Action] + [Location] + [Observed behaviour]',
      '  Good: "Checkout button proceeds with empty cart instead of showing error"',
      '  Bad: "Cart bug"',
      '',
      '**Severity:** Critical / High / Medium / Low',
      '**Priority:** P1 / P2 / P3 / P4',
      '**Environment:** Browser, OS, App version, Test environment',
      '',
      '**Steps to Reproduce:**',
      '1. Navigate to [URL]',
      '2. Click [element]',
      '3. Enter [value]',
      '4. Click [button]',
      '5. Observe the result',
      '',
      '**Expected Result:**',
      '"An error message should appear and the user should not proceed"',
      '',
      '**Actual Result:**',
      '"The checkout page loads with a £0.00 order — no error shown"',
      '',
      '**Attachments:**',
      '• Screenshot showing the bug',
      '• Video recording if it\'s a flow',
      '• Console/network errors if it\'s an API issue',
      '',
      '**Pro tip:** Make the steps so specific that a developer can reproduce it in under 1 minute without asking any questions.'
    ),
    followUps: ['What is severity vs priority?', 'Tell me about the defect lifecycle', 'What tools do QAs use to track bugs?'],
  },
  {
    id: 'severity-priority',
    patterns: ['severity vs priority', 'severity priority', 'what is severity', 'what is priority', 'bug severity', 'p1 p2', 'critical high medium low'],
    topic: 'QA Fundamentals',
    answer: a(
      '**Severity vs Priority** is a classic interview topic. ⚖️',
      '',
      '**Severity** = How badly does this break the system technically?',
      '• **Critical** — App crashes, data loss, security breach',
      '• **High** — Major feature completely broken, no workaround',
      '• **Medium** — Feature partially broken, workaround exists',
      '• **Low** — Cosmetic issue, typo, minor UX problem',
      '',
      '**Priority** = How urgently does this need to be fixed? (business decision)',
      '• **P1** — Fix immediately, block the release',
      '• **P2** — Fix in this sprint',
      '• **P3** — Fix in the next sprint',
      '• **P4** — Fix when time allows',
      '',
      '**The key insight:** They are independent.',
      '',
      '**High severity, Low priority example:**',
      "The app crashes when you enter a 500-character username. Technically Critical — but since no real user ever does this, it's Low priority to fix.",
      '',
      '**Low severity, High priority example:**',
      "The company CEO's name is misspelled on the homepage. It's a typo (Low severity) but it needs to be fixed before the board meeting tomorrow (High priority).",
      '',
      'Interviewers love this question — knowing these two examples shows you truly understand the distinction.'
    ),
    followUps: ['How do I write a bug report?', 'What is the defect lifecycle?', 'Tell me about test prioritisation'],
  },
  {
    id: 'api-testing',
    patterns: ['api testing', 'rest api', 'rest testing', 'http testing', 'api test', 'postman', 'api qa', 'api automation'],
    topic: 'QA Fundamentals',
    answer: a(
      "**API Testing** is one of the most valuable skills in modern QA — here's a complete overview: 🔌",
      '',
      '**What you\'re testing:**',
      '• **Functional** — Does the endpoint return the correct data for valid inputs?',
      '• **Negative** — Does it return appropriate errors for invalid inputs (400, 401, 403, 404)?',
      '• **Security** — Does it block unauthorised access? Can you access another user\'s data?',
      '• **Performance** — Does it respond in under 200ms under normal load?',
      '• **Contract** — Does the response shape match what the frontend expects?',
      '',
      '**HTTP status codes every QA must know:**',
      '• 200 OK, 201 Created, 204 No Content',
      '• 400 Bad Request, 401 Unauthorized, 403 Forbidden, 404 Not Found',
      '• 422 Unprocessable Entity, 429 Too Many Requests',
      '• 500 Internal Server Error, 503 Service Unavailable',
      '',
      '**Tools:**',
      '• **Postman** — GUI for exploring and testing APIs manually',
      '• **Newman** — Postman collections run from the CLI (for CI/CD)',
      '• **Playwright** — request fixture for API tests alongside E2E tests',
      '• **Supertest** — Node.js API testing library',
      '',
      '**Great security test to always run:**',
      'Try accessing /api/users/1 while authenticated as user 2. If you can see user 1\'s data, that\'s a critical IDOR (Insecure Direct Object Reference) vulnerability.',
      '',
      'Full Postman guide in **🧪 Automation Tools → Postman / Newman**.'
    ),
    followUps: ['How do I install Postman?', 'What is an IDOR vulnerability?', 'How do I test APIs in Playwright?'],
  },

  // ── Dashboard ─────────────────────────────────────────────────
  {
    id: 'dashboard',
    patterns: ['dashboard', 'home page', 'main page', 'daily challenge', 'achievements', 'streak', 'progress'],
    topic: 'Platform',
    answer: a(
      'The **Dashboard** is your command centre: 🏠',
      '',
      '**What\'s on the Dashboard:**',
      '',
      '📊 **Progress Overview** — Your current level, total XP, modules completed, and certifications earned',
      '',
      '🔥 **Streak Counter** — Days you\'ve logged in and completed at least one activity',
      '',
      '🎯 **Today\'s Challenge** — A new QA challenge every day (rotates across 7 topics). Complete it to earn 20–50 XP. Takes 5–15 minutes.',
      '',
      '🏅 **Achievements** — 12 unlockable badges for milestones: first test written, first certification, 7-day streak, capstone completed, etc.',
      '',
      '📈 **Learning Activity Graph** — Visual overview of your activity over the past month',
      '',
      '**Pro tip:** Check the Daily Challenge first thing each morning. It keeps your streak alive and accumulates XP quickly — even on days you can\'t study for hours.'
    ),
    followUps: ['How do I earn XP?', 'What are daily challenges?', 'Tell me about achievements and badges'],
  },

  // ── Fallback ──────────────────────────────────────────────────
  {
    id: 'fallback-qa-general',
    patterns: ['test', 'testing', 'quality', 'qa', 'engineer', 'software'],
    topic: 'General',
    answer: a(
      "I'm Khirad, your QA Academy assistant. Could you be a bit more specific? 😊",
      '',
      "Here are some things I can help with:",
      '• **Learning** — Modules, quizzes, study plans',
      '• **Certifications** — Which to get, how to pass',
      '• **Capstone Projects** — Finding bugs, filing reports',
      '• **Career** — Salary data, switching roles, what\'s in demand',
      '• **Tools** — Playwright, Cypress, Selenium, k6, Postman, Appium',
      '• **CI/CD** — GitHub Actions, pipelines, Docker',
      '• **AI Tools** — Claude Code, Copilot, Cursor',
      '• **Interview Prep** — Questions, answers, what to say',
      '',
      'What would you like to explore?'
    ),
    followUps: ['Tell me about career paths', 'How do I get started?', 'Which certifications are best?', 'Show me capstone projects'],
  },
];

/* ─── Matching Engine ────────────────────────────────────── */

export function findBestMatch(input: string): KBEntry {
  const query = input.toLowerCase().trim();

  const scored = knowledgeBase.map(entry => {
    let best = 0;
    for (const pattern of entry.patterns) {
      let s = 0;
      if (query === pattern) { s = 10; }
      else if (query.includes(pattern)) { s = 5 + pattern.split(' ').length; }
      else {
        const words = pattern.split(' ');
        const matched = words.filter(w => w.length > 2 && query.includes(w));
        s = (matched.length / words.length) * 3;
      }
      if (s > best) best = s;
    }
    return { entry, score: best };
  });

  scored.sort((a, b) => b.score - a.score);
  const best = scored[0];

  if (best.score < 1) {
    return knowledgeBase.find(e => e.id === 'fallback-qa-general')!;
  }
  return best.entry;
}

export const suggestedQuestions = [
  'How do I get started on QA Academy?',
  'What certifications are available?',
  'Tell me about capstone projects',
  'Which career path is right for me?',
  'How do I install Playwright?',
  'What is the STLC?',
  'How do I switch from manual QA to SDET?',
  'What salary can I earn as an SDET?',
  'How do I set up GitHub Actions for QA?',
  'What is the difference between Playwright and Cypress?',
  'Tell me about the AI chatbot capstone',
  'How does the quiz center work?',
  'What AI tools help QA engineers?',
  'Is manual QA at risk of being replaced?',
  'How do I write a good bug report?',
  'What is severity vs priority?',
];
