export interface CountryJobData {
  id: string;
  name: string;
  flag: string;
  region: string;
  currency: string;
  salaries: { junior: string; mid: string; senior: string; lead: string; sdet: string; aiEngineer: string };
  salariesUSD: { junior: string; mid: string; senior: string; lead: string; sdet: string; aiEngineer: string };
  demand: 'Very High' | 'High' | 'Medium' | 'Growing';
  remoteAvailability: 'Abundant' | 'High' | 'Moderate' | 'Limited';
  topCompanies: string[];
  hotSkills: string[];
  certifications: string[];
  jobTitles: string[];
  marketInsights: string[];
  hiringPlatforms: string[];
  visaInfo?: string;
  topCities: string[];
  outlook: string;
  avgOpenRoles?: string;
}

export const countries: CountryJobData[] = [
  {
    id: 'india',
    name: 'India',
    flag: '🇮🇳',
    region: 'Asia Pacific',
    currency: 'INR (₹)',
    salaries: { junior: '₹3–6 LPA', mid: '₹6–12 LPA', senior: '₹12–22 LPA', lead: '₹18–32 LPA', sdet: '₹10–25 LPA', aiEngineer: '₹20–45 LPA' },
    salariesUSD: { junior: '$3.6–7.2k', mid: '$7.2–14.5k', senior: '$14.5–26.5k', lead: '$21.7–38.6k', sdet: '$12–30k', aiEngineer: '$24–54k' },
    demand: 'Very High',
    remoteAvailability: 'High',
    topCompanies: ['TCS', 'Infosys', 'Wipro', 'Cognizant', 'HCL', 'Flipkart', 'Amazon India', 'Microsoft India', 'Swiggy', 'Razorpay', 'CRED', 'PhonePe', 'Zepto', 'Meesho', 'Freshworks'],
    hotSkills: ['Playwright', 'Selenium + Java', 'Python', 'API Testing', 'ISTQB', 'Appium', 'Jira', 'SQL', 'CI/CD (Jenkins)', 'AI Testing'],
    certifications: ['ISTQB CTFL', 'ISTQB CT-AI', 'AWS AI Practitioner', 'Playwright TAU'],
    jobTitles: ['QA Engineer', 'Test Analyst', 'SDET', 'Automation Engineer', 'QA Lead', 'Test Manager', 'Quality Analyst', 'Performance Test Engineer'],
    marketInsights: [
      'India has the world\'s largest QA workforce — estimated 500,000+ active QA professionals',
      'Product companies (Flipkart, Swiggy, CRED) pay 2–3x more than service companies for the same level',
      'AI testing skills command a 40–60% premium over traditional automation in 2025',
      'Bengaluru, Hyderabad and Pune drive 70% of product company hiring; Chennai and NCR lead service company volume',
      'Remote roles from US/EU companies paying in USD are highly sought — 5–10x local market rates',
    ],
    hiringPlatforms: ['LinkedIn', 'Naukri.com', 'Indeed India', 'Instahyre', 'AngelList / Wellfound', 'CutShort', 'iimjobs (lead/manager)'],
    topCities: ['Bengaluru', 'Hyderabad', 'Pune', 'Chennai', 'Mumbai', 'NCR (Noida/Gurgaon)'],
    outlook: 'India\'s QA market is booming driven by product startup growth and global AI adoption. AI testing roles growing at 80%+ YoY. Service company hiring stable; product company hiring accelerating.',
    avgOpenRoles: '80,000+ active listings on Naukri at any time',
  },
  {
    id: 'usa',
    name: 'United States',
    flag: '🇺🇸',
    region: 'North America',
    currency: 'USD ($)',
    salaries: { junior: '$65–90k', mid: '$90–130k', senior: '$130–170k', lead: '$150–200k', sdet: '$120–180k', aiEngineer: '$160–250k' },
    salariesUSD: { junior: '$65–90k', mid: '$90–130k', senior: '$130–170k', lead: '$150–200k', sdet: '$120–180k', aiEngineer: '$160–250k' },
    demand: 'Very High',
    remoteAvailability: 'Abundant',
    topCompanies: ['Google', 'Amazon', 'Meta', 'Microsoft', 'Apple', 'Salesforce', 'Netflix', 'Uber', 'Stripe', 'Databricks', 'Snowflake', 'OpenAI', 'Anthropic', 'Palantir', 'ServiceNow'],
    hotSkills: ['Playwright', 'Selenium', 'Python', 'Java', 'CI/CD (GitHub Actions)', 'AI/ML Testing', 'LLM Evaluation', 'Kubernetes', 'TypeScript', 'Performance Testing (k6)'],
    certifications: ['AWS AI Practitioner', 'AWS ML Specialty', 'Google ML Engineer', 'ISTQB CT-AI', 'CompTIA Security+', 'CSQE'],
    jobTitles: ['Software Development Engineer in Test (SDET)', 'QA Engineer', 'Software Test Engineer', 'AI Quality Engineer', 'ML Test Engineer', 'Quality Reliability Engineer (QRE)', 'Staff QA Engineer', 'Principal Test Engineer'],
    marketInsights: [
      'SDET roles in big tech (FAANG+) average $150–200k+ including equity — some senior roles exceed $300k total comp',
      'AI Quality Engineer is the fastest-growing QA title — 200%+ YoY job growth at AI companies',
      'Remote-first has increased competition but also opened access to high-paying roles for non-SF/NYC candidates',
      'Equity compensation at Series B+ startups can dwarf base salary — evaluate total comp carefully',
      'OPT/H-1B sponsorship available at larger companies; contract roles often don\'t sponsor',
    ],
    hiringPlatforms: ['LinkedIn', 'Indeed', 'Levels.fyi (salary research)', 'Glassdoor', 'Built In', 'AngelList / Wellfound (startups)', 'Dice (tech contract)'],
    visaInfo: 'H-1B, O-1, L-1 for international candidates. OPT/CPT for F-1 students. TN visa for Canadians/Mexicans.',
    topCities: ['San Francisco Bay Area', 'Seattle', 'New York', 'Austin', 'Boston', 'Chicago', 'Remote (nationwide)'],
    outlook: 'US QA market shifting heavily toward AI testing and quality engineering. Traditional manual QA declining; automation and AI QA roles surging. Total comp at top companies remains world-leading.',
    avgOpenRoles: '35,000–50,000 active QA/SDET roles at any time (LinkedIn)',
  },
  {
    id: 'uk',
    name: 'United Kingdom',
    flag: '🇬🇧',
    region: 'Europe',
    currency: 'GBP (£)',
    salaries: { junior: '£28–42k', mid: '£42–65k', senior: '£65–90k', lead: '£80–110k', sdet: '£60–100k', aiEngineer: '£90–140k' },
    salariesUSD: { junior: '$35–53k', mid: '$53–82k', senior: '$82–114k', lead: '$101–139k', sdet: '$76–127k', aiEngineer: '$114–177k' },
    demand: 'High',
    remoteAvailability: 'High',
    topCompanies: ['HSBC', 'Barclays', 'Lloyds', 'Sky', 'BT Group', 'Aviva', 'Revolut', 'Monzo', 'Deliveroo', 'Sage', 'BAE Systems', 'GCHQ/NCSC', 'NHS Digital', 'Vodafone', 'Rolls-Royce'],
    hotSkills: ['Playwright', 'Java (Selenium)', 'BDD (Cucumber)', 'API Testing', 'Accessibility (WCAG)', 'Performance Testing', 'ISTQB', 'CI/CD', 'AWS', 'Security Testing'],
    certifications: ['ISTQB CTFL', 'ISTQB CTAL-TM', 'ISTQB CT-AI', 'CompTIA Security+', 'SAFe Agilist', 'AWS certifications'],
    jobTitles: ['QA Engineer', 'Test Analyst', 'Test Consultant', 'SDET', 'Test Manager', 'QA Lead', 'Performance Test Engineer', 'Accessibility Tester', 'Test Architect'],
    marketInsights: [
      'Financial services (banking, insurance, fintech) is the dominant sector — highest salaries, strictest compliance requirements',
      'London pays 20–40% more than Manchester/Leeds/Edinburgh for equivalent roles',
      'IR35 contract rules significantly impact contracting market — umbrella/PAYE contracts now common',
      'ISTQB is more valued by UK employers than US employers — often listed as required not just preferred',
      'Government digital services (NHS, HMRC, DWP) offer stable employment but below-market pay; good for ISTQB experience',
    ],
    hiringPlatforms: ['LinkedIn', 'CWJobs', 'JobServe', 'Reed', 'TotalJobs', 'Technojobs', 'Indeed UK', 'CV-Library'],
    visaInfo: 'Skilled Worker visa required post-Brexit for non-UK/Irish nationals. Minimum salary thresholds apply (£38,700 for most roles).',
    topCities: ['London', 'Manchester', 'Edinburgh', 'Bristol', 'Birmingham', 'Leeds', 'Remote (UK-based)'],
    outlook: 'UK QA market resilient with strong fintech and regulated industries. Brexit created skills gaps opening opportunities for experienced professionals. Permanent roles stable; contracting market impacted by IR35 but recovering.',
    avgOpenRoles: '8,000–12,000 active roles (LinkedIn + job boards)',
  },
  {
    id: 'uae',
    name: 'UAE / Gulf',
    flag: '🇦🇪',
    region: 'Middle East',
    currency: 'AED (د.إ)',
    salaries: { junior: 'AED 8–15k/mo', mid: 'AED 15–25k/mo', senior: 'AED 25–40k/mo', lead: 'AED 35–55k/mo', sdet: 'AED 22–45k/mo', aiEngineer: 'AED 40–75k/mo' },
    salariesUSD: { junior: '$2.2–4.1k/mo', mid: '$4.1–6.8k/mo', senior: '$6.8–10.9k/mo', lead: '$9.5–15k/mo', sdet: '$6–12.3k/mo', aiEngineer: '$10.9–20.4k/mo' },
    demand: 'Growing',
    remoteAvailability: 'Moderate',
    topCompanies: ['Emirates', 'Etisalat (e&)', 'Du', 'ADNOC', 'FAB (First Abu Dhabi Bank)', 'ENBD', 'Careem (Uber)', 'Noon.com', 'Talabat', 'G42 (AI)', 'Dubai Holding', 'flydubai', 'Mashreq Bank'],
    hotSkills: ['Selenium', 'API Testing', 'Arabic RTL Testing', 'Mobile Testing', 'Performance Testing', 'SQL', 'Jira', 'ISTQB', 'SAP Testing', 'Security Testing'],
    certifications: ['ISTQB CTFL', 'AWS AI Practitioner', 'Azure AI-102', 'ISTQB CT-AI', 'CTAL-TM'],
    jobTitles: ['QA Engineer', 'Test Analyst', 'QA Lead', 'Test Manager', 'SDET', 'UAT Specialist', 'QA Consultant'],
    marketInsights: [
      'Tax-free salaries make UAE packages very competitive in absolute take-home terms',
      'Banking and telecom are largest sectors; G42 and UAE government AI initiatives creating AI QA demand',
      'Arabic and bilingual (Arabic/English) testing skills are a significant differentiator',
      'Most roles require on-site presence in Dubai or Abu Dhabi; limited remote options for expatriates',
      'Indian and Pakistani engineers dominate the QA workforce — strong expat community and networking',
    ],
    hiringPlatforms: ['LinkedIn', 'Bayt.com', 'GulfTalent', 'Naukrigulf', 'Indeed UAE', 'Dubizzle Jobs'],
    visaInfo: 'Employment visa sponsored by employer. Golden Visa available for highly skilled professionals. No income tax.',
    topCities: ['Dubai', 'Abu Dhabi', 'Sharjah', 'Riyadh (KSA)', 'Doha (Qatar)'],
    outlook: 'UAE AI investment (G42, ADNOC AI) is creating new AI quality engineering demand. Digital transformation across banking and government driving sustained QA hiring. Strong expat market with competitive tax-free packages.',
    avgOpenRoles: '2,000–4,000 active roles (Bayt + LinkedIn)',
  },
  {
    id: 'canada',
    name: 'Canada',
    flag: '🇨🇦',
    region: 'North America',
    currency: 'CAD (C$)',
    salaries: { junior: 'C$55–75k', mid: 'C$75–105k', senior: 'C$105–140k', lead: 'C$130–170k', sdet: 'C$100–150k', aiEngineer: 'C$140–200k' },
    salariesUSD: { junior: '$40–55k', mid: '$55–77k', senior: '$77–103k', lead: '$95–125k', sdet: '$73–110k', aiEngineer: '$103–147k' },
    demand: 'High',
    remoteAvailability: 'High',
    topCompanies: ['Shopify', 'RBC', 'TD Bank', 'CIBC', 'Scotiabank', 'Telus', 'Bell', 'OpenText', 'Hootsuite', 'Cohere', 'Ada', 'D2L', 'Government of Canada', 'CGI', 'IBM Canada'],
    hotSkills: ['Playwright', 'Selenium', 'Java/Python', 'API Testing', 'CI/CD', 'Accessibility (WCAG)', 'Bilingual (EN/FR) Testing', 'Cloud (AWS/Azure)', 'FHIR API Testing', 'AI Testing'],
    certifications: ['ISTQB CTFL', 'AWS certifications', 'Azure AI-102', 'ISTQB CT-AI', 'CSQE (ASQ)', 'SAFe Agilist'],
    jobTitles: ['QA Analyst', 'QA Engineer', 'SDET', 'Test Specialist', 'QA Lead', 'Test Manager', 'Automation Developer'],
    marketInsights: [
      'Government of Canada is a massive employer — bilingual (EN/FR) testing skills open federal contracts',
      'Toronto and Vancouver have high cost of living; many professionals choose remote and target US companies paying USD',
      'Healthcare IT and fintech are growing sectors; FHIR API testing increasingly required',
      'Canada\'s AI ecosystem (Vector Institute, Cohere, Scale AI) creating AI Quality Engineer demand in Toronto',
      'PR pathway (Express Entry) makes Canada attractive for international QA professionals — tech roles score high on CRS',
    ],
    hiringPlatforms: ['LinkedIn', 'Indeed Canada', 'Workopolis', 'Government of Canada Jobs', 'Eluta', 'Glassdoor Canada'],
    visaInfo: 'Express Entry (Federal Skilled Worker) for permanent residency. Open Work Permit for IEC/PGWP holders. Intra-company transfers.',
    topCities: ['Toronto', 'Vancouver', 'Ottawa', 'Montreal', 'Calgary', 'Waterloo/Kitchener', 'Remote'],
    outlook: 'Canada tech market recovered from 2023 layoffs. AI sector in Toronto growing strongly. Government IT modernisation driving steady demand. Remote work from Canada targeting US market remains popular.',
    avgOpenRoles: '5,000–8,000 active QA roles',
  },
  {
    id: 'australia',
    name: 'Australia',
    flag: '🇦🇺',
    region: 'Asia Pacific',
    currency: 'AUD (A$)',
    salaries: { junior: 'A$65–90k', mid: 'A$90–120k', senior: 'A$120–160k', lead: 'A$150–190k', sdet: 'A$110–160k', aiEngineer: 'A$150–220k' },
    salariesUSD: { junior: '$43–59k', mid: '$59–79k', senior: '$79–105k', lead: '$99–125k', sdet: '$73–105k', aiEngineer: '$99–145k' },
    demand: 'High',
    remoteAvailability: 'High',
    topCompanies: ['Commonwealth Bank', 'ANZ', 'NAB', 'Westpac', 'Telstra', 'Optus', 'Atlassian', 'Canva', 'REA Group', 'Seek', 'Coles', 'Woolworths Tech', 'Services Australia', 'Department of Defence'],
    hotSkills: ['Playwright', 'Cypress', 'Java/Python', 'API Testing', 'Accessibility (WCAG)', 'AWS', 'Agile/SAFe', 'CDR/Open Banking', 'Performance Testing', 'AI Testing'],
    certifications: ['ISTQB CTFL', 'AWS certifications', 'SAFe certifications', 'ISTQB CT-AI', 'CompTIA Security+'],
    jobTitles: ['QA Engineer', 'Test Analyst', 'SDET', 'QA Lead', 'Test Manager', 'Automation Engineer', 'Accessibility Tester', 'Performance Tester'],
    marketInsights: [
      'Four major banks (CBA, ANZ, NAB, Westpac) are the largest QA employers — strong compliance and automation investment',
      'Atlassian and Canva represent the high-end product company market; highly competitive but world-class engineering culture',
      'Sydney and Melbourne account for 80% of tech roles; Brisbane growing fast post-2022',
      'Accessibility testing increasingly required by law (DDA compliance) — specialist skill in demand',
      'Skilled migration pathway (482 visa) is common for QA roles; Australia is actively recruiting tech talent',
    ],
    hiringPlatforms: ['LinkedIn', 'Seek.com.au', 'Indeed Australia', 'CareerOne', 'ICT job boards', 'APS Jobs (government)'],
    visaInfo: 'TSS Visa (482) for employer-sponsored skilled workers. Global Talent Visa for highly skilled. Working Holiday for 18–35 year olds.',
    topCities: ['Sydney', 'Melbourne', 'Brisbane', 'Perth', 'Adelaide', 'Canberra (government)'],
    outlook: 'Strong QA market supported by big-4 banking compliance requirements and growing tech sector (Atlassian, Canva, Afterpay ecosystem). Migration intake supporting talent gaps. AI testing demand emerging.',
    avgOpenRoles: '4,000–7,000 active roles (Seek + LinkedIn)',
  },
  {
    id: 'germany',
    name: 'Germany',
    flag: '🇩🇪',
    region: 'Europe',
    currency: 'EUR (€)',
    salaries: { junior: '€40–55k', mid: '€55–75k', senior: '€75–100k', lead: '€90–120k', sdet: '€70–105k', aiEngineer: '€100–150k' },
    salariesUSD: { junior: '$43–59k', mid: '$59–81k', senior: '$81–108k', lead: '$97–130k', sdet: '$76–113k', aiEngineer: '$108–162k' },
    demand: 'High',
    remoteAvailability: 'Moderate',
    topCompanies: ['SAP', 'Siemens', 'BMW', 'Volkswagen', 'Bosch', 'Deutsche Bank', 'Delivery Hero', 'Zalando', 'Celonis', 'N26', 'Allianz', 'Lufthansa Systems', 'Deutsche Telekom', 'TeamViewer'],
    hotSkills: ['Java (Selenium/JUnit)', 'Python', 'SAP Testing', 'API Testing', 'CI/CD (Jenkins)', 'Jira', 'Playwright', 'Performance Testing', 'ISO 26262 (automotive)', 'ISTQB'],
    certifications: ['ISTQB CTFL', 'ISTQB CTAL-TM', 'ISTQB CT-AI', 'SAFe certifications', 'ISTQB CT-TAE'],
    jobTitles: ['QA Engineer (Qualitätsingenieur)', 'Testanalyst', 'SDET', 'Testmanager', 'QA Lead', 'Softwaretester', 'Testautomatisierungsingenieur'],
    marketInsights: [
      'Automotive sector (BMW, VW, Bosch) requires ISO 26262 functional safety testing — niche but very well paid',
      'SAP testing expertise is highly valued as Germany is SAP\'s home market with massive enterprise SAP deployments',
      'German job market favours German language skills; English-only roles exist mostly in Berlin and international tech companies',
      'Berlin startup ecosystem (Zalando, N26, Delivery Hero) operates more like US tech — English first, good equity',
      'Work-life balance is strong by law — 25+ vacation days, strict working hours regulations',
    ],
    hiringPlatforms: ['LinkedIn', 'Xing (major in Germany)', 'StepStone', 'Indeed Germany', 'Monster Germany', 'Glassdoor', 'Kimeta'],
    visaInfo: 'EU Blue Card for non-EU highly skilled workers (min €45,300/yr for ICT). Job Seeker Visa allows 6 months to find work.',
    topCities: ['Berlin', 'Munich', 'Hamburg', 'Frankfurt', 'Stuttgart', 'Cologne', 'Remote (partial)'],
    outlook: 'Germany\'s industrial and enterprise software sectors provide stable QA demand. Automotive AI testing growing with autonomous vehicle development. English-speaking roles increasing in Berlin. Strong social benefits package.',
    avgOpenRoles: '6,000–10,000 active QA roles',
  },
  {
    id: 'netherlands',
    name: 'Netherlands',
    flag: '🇳🇱',
    region: 'Europe',
    currency: 'EUR (€)',
    salaries: { junior: '€40–55k', mid: '€55–75k', senior: '€75–100k', lead: '€90–120k', sdet: '€70–105k', aiEngineer: '€100–150k' },
    salariesUSD: { junior: '$43–59k', mid: '$59–81k', senior: '$81–108k', lead: '$97–130k', sdet: '$76–113k', aiEngineer: '$108–162k' },
    demand: 'High',
    remoteAvailability: 'High',
    topCompanies: ['Booking.com', 'ASML', 'Philips', 'ING', 'ABN AMRO', 'Adyen', 'TomTom', 'Wolters Kluwer', 'Randstad', 'Coolblue', 'bol.com', 'Just Eat Takeaway'],
    hotSkills: ['Playwright', 'Selenium', 'Java/Python', 'API Testing', 'BDD (Cucumber)', 'CI/CD', 'ISTQB', 'Performance Testing', 'Agile', 'Cloud Testing'],
    certifications: ['ISTQB CTFL', 'ISTQB CTAL-TM', 'ISTQB CT-TAE', 'AWS certifications', 'SAFe'],
    jobTitles: ['Test Engineer', 'SDET', 'Test Automation Engineer', 'QA Lead', 'Test Manager', 'Test Consultant'],
    marketInsights: [
      'Netherlands is one of the highest QA salaries in Europe with the 30% tax ruling for international talent',
      'Booking.com is a world-class engineering employer — famous for strong testing culture and high engineering standards',
      'ASML (world\'s only EUV chip machine maker) pays top-of-market for embedded software QA',
      'English is widely spoken in Dutch tech companies — no Dutch required for most roles',
      '30% tax ruling gives international employees a significant net salary advantage for first 5 years',
    ],
    hiringPlatforms: ['LinkedIn', 'Indeed Netherlands', 'Glassdoor', 'Intermediair', 'Nationale Vacaturebank', 'ITProfessional.nl'],
    visaInfo: 'Highly Skilled Migrant Visa (HSM) — fast-track, 2-week processing. 30% tax ruling for qualified international recruits.',
    topCities: ['Amsterdam', 'Eindhoven', 'Delft/Den Haag', 'Utrecht', 'Rotterdam', 'Remote'],
    outlook: 'Netherlands remains a top European destination for QA talent. Strong English-language tech market, world-class employers, and attractive tax benefits for international professionals.',
    avgOpenRoles: '3,000–5,000 active roles',
  },
  {
    id: 'singapore',
    name: 'Singapore',
    flag: '🇸🇬',
    region: 'Asia Pacific',
    currency: 'SGD (S$)',
    salaries: { junior: 'S$50–75k', mid: 'S$75–110k', senior: 'S$110–155k', lead: 'S$140–190k', sdet: 'S$100–160k', aiEngineer: 'S$150–230k' },
    salariesUSD: { junior: '$37–55k', mid: '$55–81k', senior: '$81–114k', lead: '$103–140k', sdet: '$73–118k', aiEngineer: '$110–169k' },
    demand: 'High',
    remoteAvailability: 'Moderate',
    topCompanies: ['DBS', 'OCBC', 'UOB', 'Grab', 'Sea (Shopee)', 'Lazada', 'Singtel', 'GovTech', 'Razer', 'Garena', 'Carousell', 'Ninja Van', 'Standard Chartered', 'Citi Singapore'],
    hotSkills: ['Playwright', 'Java/Python', 'API Testing', 'Mobile Testing', 'Cloud (AWS/GCP)', 'AI Testing', 'Accessibility', 'CI/CD', 'Kubernetes', 'ISTQB'],
    certifications: ['ISTQB CTFL', 'AWS certifications', 'Google ML Engineer', 'ISTQB CT-AI', 'Azure AI-102'],
    jobTitles: ['QA Engineer', 'SDET', 'Test Engineer', 'QA Lead', 'Quality Reliability Engineer', 'AI Test Engineer'],
    marketInsights: [
      'Singapore is the Asia-Pacific HQ for most major tech companies — regional QA leadership roles based here',
      'GovTech Singapore is a world-class government digital agency paying competitive market rates',
      'CPF (mandatory pension) adds ~17% employer cost on top of salary — factor into total compensation',
      'AI and fintech are the hottest growth sectors; Grab and Sea Group are regional tech giants with world-class engineering',
      'Employment Pass (EP) allows foreign professionals to work; minimum qualifying salary raised to S$5,000/month in 2025',
    ],
    hiringPlatforms: ['LinkedIn', 'MyCareersFuture.sg (government)', 'Jobstreet', 'JobsDB', 'Glassdoor', 'Indeed Singapore'],
    visaInfo: 'Employment Pass (EP) for professionals earning S$5,000+/month. S Pass for mid-skill. Tech.Pass for top tech talent.',
    topCities: ['Singapore (city-state)'],
    outlook: 'Singapore cements its position as Asia\'s premium tech hub. Strong government AI investment (National AI Strategy 2.0) driving AI QA demand. Competitive salaries and excellent quality of life sustain talent attraction.',
    avgOpenRoles: '2,000–4,000 active roles',
  },
  {
    id: 'poland',
    name: 'Poland',
    flag: '🇵🇱',
    region: 'Europe',
    currency: 'PLN (zł)',
    salaries: { junior: 'zł 6–10k/mo', mid: 'zł 10–17k/mo', senior: 'zł 17–25k/mo', lead: 'zł 22–30k/mo', sdet: 'zł 15–25k/mo', aiEngineer: 'zł 22–35k/mo' },
    salariesUSD: { junior: '$15–25k', mid: '$25–43k', senior: '$43–63k', lead: '$55–76k', sdet: '$38–63k', aiEngineer: '$55–88k' },
    demand: 'High',
    remoteAvailability: 'Abundant',
    topCompanies: ['Allegro', 'OLX', 'CD Projekt', 'Comarch', 'Asseco', 'Epam Systems', 'Luxoft', 'Capgemini Poland', 'Nokia', 'Samsung R&D Poland', 'Google Poland', 'Allegro Pay', 'PKO Bank Polski'],
    hotSkills: ['Playwright', 'Selenium + Java', 'Python', 'API Testing', 'BDD', 'CI/CD', 'Docker', 'Kubernetes', 'ISTQB', 'AI Testing'],
    certifications: ['ISTQB CTFL', 'ISTQB CT-TAE', 'ISTQB CT-AI', 'AWS certifications', 'SAFe'],
    jobTitles: ['QA Engineer', 'Tester Oprogramowania', 'SDET', 'Test Automation Engineer', 'QA Lead', 'Test Manager'],
    marketInsights: [
      'Poland is Western Europe\'s largest nearshore IT hub — major cost advantage while still in EU timezone',
      'B2B contracting is extremely common — most experienced Polish QA professionals work as self-employed contractors',
      'Remote work culture is mature — most Polish IT companies offer full remote or hybrid for tech roles',
      'Warsaw and Krakow are the main hubs; Wroclaw and Poznan growing quickly with strong university pipelines',
      'Strong ISTQB culture — Polish Testing Board is active; ISTQB expected for most roles above junior',
    ],
    hiringPlatforms: ['LinkedIn', 'No Fluff Jobs (tech-focused)', 'JustJoin.it', 'Pracuj.pl', 'Bulldogjob', 'Indeed Poland'],
    topCities: ['Warsaw', 'Krakow', 'Wroclaw', 'Poznan', 'Gdansk', 'Remote (from anywhere)'],
    outlook: 'Poland\'s QA market benefits from EU membership, strong technical education, and competitive nearshore rates. AI adoption across Polish tech companies creating AI quality demand. B2B contracting rates remain attractive for experienced professionals.',
    avgOpenRoles: '5,000–9,000 active roles',
  },
  {
    id: 'pakistan',
    name: 'Pakistan',
    flag: '🇵🇰',
    region: 'Asia Pacific',
    currency: 'PKR (₨)',
    salaries: { junior: '₨ 80–150k/mo', mid: '₨ 150–300k/mo', senior: '₨ 300–500k/mo', lead: '₨ 450–700k/mo', sdet: '₨ 250–500k/mo', aiEngineer: '₨ 400–800k/mo' },
    salariesUSD: { junior: '$300–550/mo', mid: '$550–1,100/mo', senior: '$1,100–1,800/mo', lead: '$1,600–2,500/mo', sdet: '$900–1,800/mo', aiEngineer: '$1,500–3,000/mo' },
    demand: 'Growing',
    remoteAvailability: 'Abundant',
    topCompanies: ['Systems Limited', 'NETSOL Technologies', 'Ibex', 'TRG Pakistan', 'Arbisoft', '10Pearls', 'Contour Software', 'Techlogix', 'Programmers Force', 'Devsinc'],
    hotSkills: ['Selenium', 'Playwright', 'API Testing (Postman)', 'Python', 'Manual Testing', 'ISTQB', 'Jira', 'SQL', 'Appium', 'Remote QA (Upwork/Toptal)'],
    certifications: ['ISTQB CTFL', 'Postman Expert', 'Playwright TAU', 'AWS AI Practitioner', 'ISTQB CT-AI'],
    jobTitles: ['QA Engineer', 'Software Test Engineer', 'QA Analyst', 'SDET', 'Manual Tester', 'Automation Engineer'],
    marketInsights: [
      'Remote work for US/EU clients at international rates is the primary income maximisation strategy — 5–10x local rates',
      'Freelancing platforms (Upwork, Toptal, Fiverr) are major QA employment channels alongside full-time employment',
      'Lahore, Karachi, and Islamabad are the IT hubs with LUMS, FAST, and NUST producing strong engineering graduates',
      'Currency depreciation means USD-earning remote workers have seen significant purchasing power growth',
      'ISTQB Foundation is highly valued for credibility in international hiring — strong ROI for Pakistani QA professionals',
    ],
    hiringPlatforms: ['LinkedIn', 'Rozee.pk', 'Mustakbil', 'Indeed Pakistan', 'Upwork', 'Toptal', 'Freelancer.com'],
    topCities: ['Lahore', 'Karachi', 'Islamabad', 'Rawalpindi', 'Remote (international clients)'],
    outlook: 'Pakistan IT export market growing rapidly with government support. Remote QA roles from US/EU companies pay well above domestic market. AI testing skills create significant earning potential for forward-looking QA engineers.',
    avgOpenRoles: '3,000–6,000 on local platforms; unlimited remote opportunities',
  },
  {
    id: 'southafrica',
    name: 'South Africa',
    flag: '🇿🇦',
    region: 'Africa',
    currency: 'ZAR (R)',
    salaries: { junior: 'R 250–400k/yr', mid: 'R 400–650k/yr', senior: 'R 650–900k/yr', lead: 'R 800–1.1M/yr', sdet: 'R 600–950k/yr', aiEngineer: 'R 900–1.4M/yr' },
    salariesUSD: { junior: '$13–21k', mid: '$21–35k', senior: '$35–48k', lead: '$43–59k', sdet: '$32–51k', aiEngineer: '$48–75k' },
    demand: 'Medium',
    remoteAvailability: 'High',
    topCompanies: ['Standard Bank', 'FNB (FirstRand)', 'Absa', 'Nedbank', 'MTN', 'Vodacom', 'Discovery', 'Shoprite', 'Naspers/Prosus', 'BCX', 'Dimension Data', 'Accenture SA', 'AWS South Africa'],
    hotSkills: ['Selenium', 'Java', 'API Testing', 'SQL', 'Python', 'Manual Testing', 'ISTQB', 'Mobile Testing', 'AWS', 'Agile (SAFe)'],
    certifications: ['ISTQB CTFL', 'AWS certifications', 'ISTQB CT-TAE', 'SAFe Agilist', 'CompTIA Security+'],
    jobTitles: ['QA Engineer', 'Test Analyst', 'QA Lead', 'Test Manager', 'SDET', 'Automation Tester', 'UAT Analyst'],
    marketInsights: [
      'South African QA rates are very competitive for international remote work — significant geographic arbitrage opportunity',
      'Financial services (Big-4 banks, Discovery, Old Mutual) is the dominant QA employer with strict compliance needs',
      'Cape Town has a growing startup ecosystem; Johannesburg dominates enterprise/banking tech',
      'Load shedding infrastructure challenges have accelerated cloud adoption — cloud testing skills increasingly valued',
      'Remote work for UK/US companies at international rates is a strong career strategy given ZAR/USD exchange rate',
    ],
    hiringPlatforms: ['LinkedIn', 'Careers24', 'Pnet', 'Indeed SA', 'OfferZen (tech-focused, top choice)', 'ITWeb Careers'],
    visaInfo: 'Critical Skills Visa for software professionals. General Work Visa for employer-sponsored roles.',
    topCities: ['Johannesburg', 'Cape Town', 'Pretoria', 'Durban', 'Remote (international)'],
    outlook: 'SA QA market offers strong opportunity for international remote work. Domestic market stable, led by financial services. AI adoption accelerating. Geographic arbitrage makes SA professionals very attractive to global employers.',
    avgOpenRoles: '1,500–3,000 active roles',
  },
];

export const globalStats = {
  totalJobsEstimate: '180,000+',
  avgGrowthRate: '22% YoY (AI testing roles)',
  topSkill2025: 'AI / LLM Testing',
  fastestGrowingRole: 'AI Quality Engineer (+200% YoY)',
  remotePercentage: '45%',
  avgSalaryUSA: '$130k (senior)',
  certMostValued: 'ISTQB CTFL (globally)',
};

export interface HotJobTitle {
  title: string;
  description: string;
  avgSalaryUSD: string;
  growth: string;
  level: string;
  skills: string[];
  color: string;
}

export const hotJobTitles: HotJobTitle[] = [
  { title: 'AI Quality Engineer', description: 'Tests LLMs, RAG systems, agents and AI pipelines for accuracy, safety, and reliability', avgSalaryUSD: '$140–250k (USA)', growth: '+200% YoY', level: 'Senior/Expert', skills: ['LLM Evaluation', 'Python', 'Prompt Testing', 'Red Teaming', 'ISTQB CT-AI'], color: '#a855f7' },
  { title: 'SDET (Software Dev Engineer in Test)', description: 'Builds test frameworks, automation infrastructure and quality tools alongside product engineers', avgSalaryUSD: '$120–180k (USA)', growth: '+35% YoY', level: 'Mid/Senior', skills: ['Playwright', 'Java/Python', 'CI/CD', 'Docker', 'API Testing'], color: '#6366f1' },
  { title: 'MLOps QA Engineer', description: 'Validates ML pipelines, model drift detection, data quality and production AI systems', avgSalaryUSD: '$130–200k (USA)', growth: '+150% YoY', level: 'Senior/Expert', skills: ['Python', 'ML Pipelines', 'Data Quality', 'AWS/GCP', 'Monitoring'], color: '#ec4899' },
  { title: 'Performance Test Engineer', description: 'Designs and executes load, stress, and soak tests to validate system performance under scale', avgSalaryUSD: '$100–150k (USA)', growth: '+20% YoY', level: 'Mid/Senior', skills: ['k6', 'JMeter', 'Gatling', 'Cloud Load Testing', 'Observability'], color: '#f59e0b' },
  { title: 'Automation Architect', description: 'Designs enterprise test automation frameworks, standards, and CI/CD quality gates at organisational scale', avgSalaryUSD: '$140–190k (USA)', growth: '+25% YoY', level: 'Principal/Architect', skills: ['Framework Design', 'Multiple Tools', 'CI/CD Architecture', 'Mentoring'], color: '#10b981' },
  { title: 'Security Test Engineer', description: 'Performs penetration testing, vulnerability assessment, and security validation for web and API applications', avgSalaryUSD: '$110–160k (USA)', growth: '+40% YoY', level: 'Mid/Senior', skills: ['OWASP ZAP', 'Burp Suite', 'Python', 'OWASP Top 10', 'CompTIA Security+'], color: '#ef4444' },
  { title: 'Senior QA Engineer', description: 'Leads quality strategy, mentors juniors, drives automation and works closely with product and dev teams', avgSalaryUSD: '$110–160k (USA)', growth: '+18% YoY', level: 'Senior', skills: ['Playwright/Selenium', 'Test Strategy', 'API Testing', 'Mentoring', 'ISTQB'], color: '#3b82f6' },
  { title: 'QA Lead', description: 'Leads a team of QA engineers, owns test strategy, stakeholder communication and release quality decisions', avgSalaryUSD: '$120–170k (USA)', growth: '+15% YoY', level: 'Lead', skills: ['Team Leadership', 'Test Strategy', 'Metrics', 'Automation Oversight', 'Agile'], color: '#f97316' },
  { title: 'QA Manager', description: 'Manages QA department, builds the business case for quality investment, and owns quality KPIs at org level', avgSalaryUSD: '$130–190k (USA)', growth: '+12% YoY', level: 'Manager', skills: ['People Management', 'Budget', 'Risk Management', 'OKRs', 'Executive Reporting'], color: '#d97706' },
  { title: 'Junior QA Engineer', description: 'Executes test cases, logs defects, learns automation, and contributes to sprint testing activities', avgSalaryUSD: '$55–85k (USA)', growth: '+10% YoY', level: 'Junior', skills: ['Manual Testing', 'Jira', 'API Basics', 'ISTQB CTFL', 'SQL'], color: '#64748b' },
];

export interface SkillDemand {
  skill: string;
  category: string;
  demand: number;
  trend: 'Rising' | 'Stable' | 'Declining';
  note: string;
}

export const skillDemand: SkillDemand[] = [
  { skill: 'AI / LLM Testing', category: 'AI Testing', demand: 97, trend: 'Rising', note: 'Fastest-growing skill in QA market globally' },
  { skill: 'Playwright', category: 'Automation', demand: 91, trend: 'Rising', note: 'Overtaking Selenium as the default automation framework in 2024–25' },
  { skill: 'Python', category: 'Programming', demand: 88, trend: 'Rising', note: 'Essential for AI testing, API testing, and modern automation' },
  { skill: 'API Testing (REST/GraphQL)', category: 'Testing', demand: 87, trend: 'Stable', note: 'Core skill required at virtually every level' },
  { skill: 'CI/CD Integration', category: 'DevOps', demand: 85, trend: 'Rising', note: 'Shift-left mandates CI-integrated test suites' },
  { skill: 'TypeScript', category: 'Programming', demand: 82, trend: 'Rising', note: 'Standard language for Playwright and modern JS test frameworks' },
  { skill: 'Selenium + Java', category: 'Automation', demand: 78, trend: 'Stable', note: 'Still dominant in enterprise and India service companies' },
  { skill: 'LLM Evaluation', category: 'AI Testing', demand: 76, trend: 'Rising', note: 'Golden datasets, LLM-as-judge, hallucination testing' },
  { skill: 'Docker / Kubernetes', category: 'DevOps', demand: 73, trend: 'Rising', note: 'Test environment management and containerised test execution' },
  { skill: 'Performance Testing (k6)', category: 'Testing', demand: 70, trend: 'Rising', note: 'k6 rapidly replacing JMeter for cloud-native load testing' },
  { skill: 'ISTQB Certification', category: 'Certification', demand: 68, trend: 'Stable', note: 'Expected in India/UK/Europe; less critical in US startups' },
  { skill: 'Security Testing (OWASP)', category: 'Testing', demand: 65, trend: 'Rising', note: 'AppSec integration into QA pipelines accelerating' },
  { skill: 'Prompt Injection Testing', category: 'AI Testing', demand: 62, trend: 'Rising', note: 'OWASP LLM Top 10 driving security-focused AI testing' },
  { skill: 'Cypress', category: 'Automation', demand: 60, trend: 'Stable', note: 'Strong in React/Vue frontend shops; losing ground to Playwright' },
  { skill: 'Accessibility Testing (WCAG)', category: 'Testing', demand: 58, trend: 'Rising', note: 'Legal requirements (ADA, DDA, EAA) driving mandatory adoption' },
  { skill: 'Mobile Testing (Appium)', category: 'Mobile', demand: 55, trend: 'Stable', note: 'Required wherever mobile is a primary channel' },
  { skill: 'JMeter', category: 'Performance', demand: 45, trend: 'Declining', note: 'Being replaced by k6 and Gatling in modern stacks' },
  { skill: 'Java (legacy Selenium)', category: 'Programming', demand: 42, trend: 'Declining', note: 'Still required for legacy enterprise but new projects choose Python/TS' },
];
