export interface Module {
  id: number;
  title: string;
  subtitle: string;
  icon: string;
  track: 'core' | 'automation' | 'ai-quality' | 'specialized' | 'leadership' | 'ai-builder';
  difficulty: string;
  duration: string;
  topics: string[];
  labs: string[];
  tools?: string[];
  color: string;
  gradient: string;
}

export const modules: Module[] = [
  {
    id: 1,
    title: 'Software Testing Fundamentals',
    subtitle: 'SDLC, STLC, Defect Lifecycle & Core Concepts',
    icon: '🧪',
    track: 'core',
    difficulty: 'Beginner',
    duration: '4 hours',
    topics: ['SDLC', 'STLC', 'Defect Lifecycle', 'Verification vs Validation', 'QA vs QC', 'Testing Principles', 'Test Planning', 'Test Strategy', 'Test Scenarios', 'Test Cases', 'Bug Reporting'],
    labs: ['Create Test Cases from Requirements', 'Report Bugs with Severity & Priority', 'Review Requirements for Gaps'],
    color: '#6366f1',
    gradient: 'from-indigo-500 to-purple-600',
  },
  {
    id: 2,
    title: 'Manual Testing Mastery',
    subtitle: 'Functional, Regression, Exploratory & UAT',
    icon: '🔍',
    track: 'core',
    difficulty: 'Beginner',
    duration: '5 hours',
    topics: ['Functional Testing', 'Smoke Testing', 'Sanity Testing', 'Regression Testing', 'UAT', 'Exploratory Testing', 'Ad Hoc Testing', 'Risk Based Testing'],
    labs: ['E-commerce Testing Lab', 'CRM Testing Lab', 'Healthcare Portal Lab', 'LMS Testing Lab'],
    color: '#8b5cf6',
    gradient: 'from-purple-500 to-pink-600',
  },
  {
    id: 3,
    title: 'Advanced Test Design',
    subtitle: 'BVA, EP, State Transition & Decision Tables',
    icon: '📐',
    track: 'core',
    difficulty: 'Intermediate',
    duration: '4 hours',
    topics: ['Boundary Value Analysis', 'Equivalence Partitioning', 'State Transition', 'Decision Tables', 'Pairwise Testing', 'Cause Effect Graphing', 'Error Guessing'],
    labs: ['Design Optimal Test Coverage', 'State Transition Modeling', 'Decision Table Lab'],
    color: '#06b6d4',
    gradient: 'from-cyan-500 to-blue-600',
  },
  {
    id: 4,
    title: 'API Testing',
    subtitle: 'REST, GraphQL, gRPC, Postman & Security',
    icon: '🔌',
    track: 'core',
    difficulty: 'Intermediate',
    duration: '6 hours',
    topics: ['REST API Testing', 'SOAP', 'GraphQL', 'gRPC', 'Authentication & JWT', 'OAuth 2.0', 'Rate Limiting', 'Pagination', 'API Security'],
    labs: ['Real API Testing Lab', 'Mock API Lab', 'Broken API Bug Hunt'],
    tools: ['Postman', 'Swagger', 'Bruno', 'Insomnia'],
    color: '#10b981',
    gradient: 'from-emerald-500 to-teal-600',
  },
  {
    id: 5,
    title: 'Database Testing',
    subtitle: 'SQL, Joins, Stored Procedures & Data Validation',
    icon: '🗄️',
    track: 'core',
    difficulty: 'Intermediate',
    duration: '5 hours',
    topics: ['SQL Fundamentals', 'Joins & Subqueries', 'Stored Procedures', 'Triggers', 'Data Validation', 'Data Migration Testing'],
    labs: ['Data Integrity Validation Lab', 'Backend Verification Lab', 'Migration Testing Lab'],
    tools: ['MySQL', 'PostgreSQL', 'SQL Server', 'MongoDB'],
    color: '#f59e0b',
    gradient: 'from-amber-500 to-orange-600',
  },
  {
    id: 6,
    title: 'Playwright Automation',
    subtitle: 'Architecture, POM, CI/CD & AI Test Generation',
    icon: '🎭',
    track: 'automation',
    difficulty: 'Intermediate',
    duration: '8 hours',
    topics: ['Installation & Setup', 'Architecture', 'Selectors & Locators', 'Assertions', 'Fixtures & Hooks', 'Page Object Model', 'API Testing', 'Parallel Execution', 'CI/CD Integration', 'Docker', 'Reporting'],
    labs: ['Shopify Automation Project', 'SaaS Platform Testing', 'CRM Automation'],
    tools: ['Playwright', 'TypeScript', 'GitHub Actions', 'Docker'],
    color: '#3b82f6',
    gradient: 'from-blue-500 to-indigo-600',
  },
  {
    id: 7,
    title: 'Cypress Automation',
    subtitle: 'Commands, Network Stubbing & E2E Testing',
    icon: '🌲',
    track: 'automation',
    difficulty: 'Intermediate',
    duration: '5 hours',
    topics: ['Cypress Architecture', 'Commands & Queries', 'Fixtures', 'Network Stubbing', 'Interceptors', 'Cypress vs Playwright'],
    labs: ['E-commerce E2E Testing', 'Admin Portal Testing'],
    tools: ['Cypress', 'JavaScript', 'Mocha'],
    color: '#22c55e',
    gradient: 'from-green-500 to-emerald-600',
  },
  {
    id: 8,
    title: 'Mobile Testing',
    subtitle: 'Android, iOS, Appium & Maestro',
    icon: '📱',
    track: 'specialized',
    difficulty: 'Advanced',
    duration: '6 hours',
    topics: ['Android Testing', 'iOS Testing', 'Device Farm', 'Gesture Testing', 'Offline Testing', 'Performance on Mobile'],
    labs: ['Native App Testing Lab', 'Gesture & Interaction Lab', 'Offline Mode Testing'],
    tools: ['Appium', 'Maestro', 'Android Studio', 'Xcode'],
    color: '#ec4899',
    gradient: 'from-pink-500 to-rose-600',
  },
  {
    id: 9,
    title: 'AI Testing Fundamentals',
    subtitle: 'ML Systems, LLMs, Hallucination & Bias',
    icon: '🤖',
    track: 'ai-quality',
    difficulty: 'Advanced',
    duration: '5 hours',
    topics: ['AI System Architecture', 'ML Systems', 'LLM Systems', 'Generative AI', 'Hallucination', 'Bias & Fairness', 'Model Drift', 'Explainability'],
    labs: ['Identify AI Failures Lab', 'Hallucination Detection', 'Bias Audit Lab'],
    color: '#a855f7',
    gradient: 'from-violet-500 to-purple-700',
  },
  {
    id: 10,
    title: 'Prompt Engineering for QA',
    subtitle: 'System Prompts, Chain of Thought & QA Generators',
    icon: '💬',
    track: 'ai-quality',
    difficulty: 'Advanced',
    duration: '4 hours',
    topics: ['Prompt Design Principles', 'System Prompts', 'Role Prompting', 'Chain of Thought', 'Few Shot Learning', 'Prompt Chaining'],
    labs: ['Build a QA Test Generator', 'Test Case Prompt Lab', 'Bug Report Generator'],
    color: '#f97316',
    gradient: 'from-orange-500 to-red-600',
  },
  {
    id: 11,
    title: 'LLM Testing',
    subtitle: 'Hallucination, Toxicity, Prompt Injection & Jailbreaks',
    icon: '🧠',
    track: 'ai-quality',
    difficulty: 'Expert',
    duration: '7 hours',
    topics: ['Response Accuracy Testing', 'Hallucination Detection', 'Toxicity Testing', 'Prompt Injection', 'Jailbreak Testing', 'Adversarial Inputs'],
    labs: ['Healthcare AI Testing', 'Legal AI Testing', 'Customer Support AI Testing', 'Break the AI Lab — 25+ vulnerabilities'],
    color: '#ef4444',
    gradient: 'from-red-500 to-rose-700',
  },
  {
    id: 12,
    title: 'RAG System Testing',
    subtitle: 'Embeddings, Vector DBs, Retrieval & Citation Validation',
    icon: '📡',
    track: 'ai-quality',
    difficulty: 'Expert',
    duration: '6 hours',
    topics: ['Embeddings & Vectors', 'Vector Databases', 'Retrieval Layer Testing', 'Context Window Management', 'Retrieval Accuracy', 'Context Precision', 'Citation Validation', 'Grounded Responses'],
    labs: ['Broken RAG System Lab', 'Missing Context Detection', 'Incorrect Retrieval Hunt', 'Duplicate Retrieval Lab'],
    tools: ['Pinecone', 'Weaviate', 'Chroma', 'Qdrant'],
    color: '#0ea5e9',
    gradient: 'from-sky-500 to-blue-700',
  },
  {
    id: 13,
    title: 'Agentic AI Testing',
    subtitle: 'Multi-Agent Systems, CrewAI, LangGraph & AutoGen',
    icon: '🤝',
    track: 'ai-quality',
    difficulty: 'Expert',
    duration: '7 hours',
    topics: ['AI Agent Architecture', 'Multi-Agent Systems', 'Agent Orchestration', 'Planning & Reasoning', 'Memory Management', 'Tool Usage', 'Agent Communication'],
    labs: ['Agent Failure Detection Lab', 'Multi-Agent Workflow Testing', 'Tool Calling Validation'],
    tools: ['CrewAI', 'LangGraph', 'AutoGen', 'LangChain'],
    color: '#14b8a6',
    gradient: 'from-teal-500 to-cyan-700',
  },
  {
    id: 14,
    title: 'MCP Testing',
    subtitle: 'Model Context Protocol — Tool Discovery & Failure Handling',
    icon: '🔗',
    track: 'ai-quality',
    difficulty: 'Expert',
    duration: '5 hours',
    topics: ['Model Context Protocol', 'Tool Discovery & Registration', 'Tool Execution Testing', 'Authentication & Permissions', 'Context Failures', 'Tool Routing Issues'],
    labs: ['Broken MCP Server Lab', 'Context Failure Detection', 'Tool Routing Bug Hunt', 'Permission Testing Lab'],
    color: '#8b5cf6',
    gradient: 'from-violet-600 to-indigo-700',
  },
  {
    id: 15,
    title: 'AI Security Testing',
    subtitle: 'Prompt Injection, Data Leakage & Adversarial Attacks',
    icon: '🛡️',
    track: 'ai-quality',
    difficulty: 'Expert',
    duration: '6 hours',
    topics: ['Prompt Injection Attacks', 'Data Leakage', 'Model Poisoning', 'Jailbreak Techniques', 'Adversarial Inputs', 'Red Teaming AI'],
    labs: ['Attack an AI System Lab', 'Prompt Injection Lab', 'Data Exfiltration Testing'],
    color: '#dc2626',
    gradient: 'from-red-600 to-rose-800',
  },
  {
    id: 16,
    title: 'AI Observability',
    subtitle: 'Monitoring, Tracing, Cost Tracking & LangSmith',
    icon: '📊',
    track: 'ai-quality',
    difficulty: 'Expert',
    duration: '4 hours',
    topics: ['AI System Monitoring', 'Distributed Tracing', 'Cost Tracking', 'Latency Analysis', 'Drift Detection', 'Quality Dashboards'],
    labs: ['LangSmith Integration Lab', 'Observability Dashboard Lab', 'Cost Optimization Lab'],
    tools: ['LangSmith', 'LangFuse', 'Helicone', 'Grafana'],
    color: '#7c3aed',
    gradient: 'from-purple-600 to-violet-800',
  },
  {
    id: 17,
    title: 'Performance Testing',
    subtitle: 'Load, Stress, Spike & Endurance with K6 & JMeter',
    icon: '⚡',
    track: 'specialized',
    difficulty: 'Advanced',
    duration: '6 hours',
    topics: ['Load Testing', 'Stress Testing', 'Spike Testing', 'Endurance Testing', 'Bottleneck Analysis', 'Performance Metrics'],
    labs: ['System Failure Simulation', 'Load Test a REST API', 'Database Performance Lab'],
    tools: ['JMeter', 'K6', 'Locust', 'Gatling'],
    color: '#f59e0b',
    gradient: 'from-yellow-500 to-amber-700',
  },
  {
    id: 18,
    title: 'Security Testing',
    subtitle: 'OWASP Top 10, Auth, SQL Injection & Session Management',
    icon: '🔒',
    track: 'specialized',
    difficulty: 'Advanced',
    duration: '6 hours',
    topics: ['OWASP Top 10', 'SQL Injection', 'XSS', 'CSRF', 'Authentication Testing', 'Authorization Testing', 'Session Management'],
    labs: ['Find Security Vulnerabilities Lab', 'OWASP Juice Shop', 'Auth Bypass Lab'],
    tools: ['OWASP ZAP', 'Burp Suite', 'Nmap'],
    color: '#b91c1c',
    gradient: 'from-red-700 to-rose-900',
  },
  {
    id: 19,
    title: 'Accessibility Testing',
    subtitle: 'WCAG, Screen Readers, Keyboard Nav & Color Contrast',
    icon: '♿',
    track: 'specialized',
    difficulty: 'Intermediate',
    duration: '4 hours',
    topics: ['WCAG Guidelines', 'Screen Reader Testing', 'Keyboard Navigation', 'Color Contrast', 'ARIA Labels', 'Focus Management'],
    labs: ['Accessibility Audit Lab', 'Screen Reader Testing Lab', 'Keyboard Navigation Lab'],
    tools: ['Axe', 'Lighthouse', 'NVDA', 'VoiceOver'],
    color: '#059669',
    gradient: 'from-emerald-600 to-green-800',
  },
  {
    id: 20,
    title: 'DevOps for QA',
    subtitle: 'Git, GitHub Actions, Docker, Kubernetes & CI/CD',
    icon: '🚀',
    track: 'specialized',
    difficulty: 'Advanced',
    duration: '7 hours',
    topics: ['Git & GitHub', 'CI/CD Pipelines', 'Docker for Testing', 'Kubernetes', 'Infrastructure as Code', 'Shift-Left Testing'],
    labs: ['Deploy Automation Framework', 'GitHub Actions Pipeline Lab', 'Docker Test Environment Lab'],
    tools: ['GitHub Actions', 'Docker', 'Kubernetes', 'Terraform'],
    color: '#2563eb',
    gradient: 'from-blue-600 to-indigo-800',
  },
  {
    id: 21,
    title: 'QA Leadership & Strategy',
    subtitle: 'Test Metrics, Risk Analysis, Team Management & AI Adoption',
    icon: '👑',
    track: 'leadership',
    difficulty: 'QA Lead / Manager',
    duration: '6 hours',
    topics: ['QA Strategy Design', 'Test Metrics & KPIs', 'Risk Analysis', 'Team Management', 'AI Adoption Strategy', 'Vendor Assessment', 'Budget Planning'],
    labs: ['Create Enterprise QA Strategy', 'Build a QA Dashboard', 'Risk Register Lab'],
    color: '#d97706',
    gradient: 'from-amber-600 to-yellow-700',
  },
  {
    id: 22,
    title: 'Building Agentic AI Systems',
    subtitle: 'Architecture, Components, Memory, Tools & Step-by-Step Build Guide',
    icon: '🏗️',
    track: 'ai-builder',
    difficulty: 'Advanced',
    duration: '8 hours',
    topics: [
      'What is an AI Agent?',
      'Agent Architecture Patterns',
      'Perception — Input Processing',
      'Reasoning & Planning (ReAct, CoT)',
      'Memory Systems (Short-term, Long-term, Episodic)',
      'Tool Use & Function Calling',
      'Action Execution',
      'Multi-Agent Orchestration',
      'Agent Loops & Termination',
      'Error Handling & Fallbacks',
      'Evaluation & Evals Framework',
      'Deploying Agents to Production',
    ],
    labs: [
      'Build a Research Agent from Scratch',
      'Add Memory to a Stateless Agent',
      'Multi-Agent Pipeline Lab',
      'Agent Failure Recovery Lab',
      'Production Deployment Checklist',
    ],
    tools: ['LangChain', 'LangGraph', 'OpenAI SDK', 'Anthropic SDK', 'CrewAI'],
    color: '#6366f1',
    gradient: 'from-indigo-500 to-violet-700',
  },
  {
    id: 23,
    title: 'AI Workflow Automation',
    subtitle: 'LangGraph, CrewAI, n8n, Make & No-Code to Pro-Code Workflows',
    icon: '⚙️',
    track: 'ai-builder',
    difficulty: 'Advanced',
    duration: '7 hours',
    topics: [
      'What is an AI Workflow?',
      'No-Code Workflows: n8n & Make (Integromat)',
      'Low-Code: Flowise & Langflow',
      'Pro-Code: LangGraph State Machines',
      'CrewAI Role-Based Workflows',
      'Sequential vs Parallel vs Hierarchical Flows',
      'Conditional Branching & Routing',
      'Human-in-the-Loop Approval Steps',
      'Retry Logic & Error Nodes',
      'Webhook Triggers & Scheduling',
      'Connecting Workflows to APIs & Databases',
      'Testing & Monitoring Workflows',
    ],
    labs: [
      'Build a Bug Triage Workflow in n8n',
      'Automate Test Report Generation',
      'LangGraph Sequential QA Pipeline',
      'CrewAI QA Review Crew',
      'Human-in-the-Loop Approval Lab',
    ],
    tools: ['n8n', 'Make', 'LangGraph', 'CrewAI', 'Flowise', 'Zapier'],
    color: '#0ea5e9',
    gradient: 'from-sky-500 to-cyan-700',
  },
  {
    id: 24,
    title: 'Tool Integration & MCP',
    subtitle: 'Connect AI to Real Systems — APIs, Databases, Browsers & Code',
    icon: '🔧',
    track: 'ai-builder',
    difficulty: 'Expert',
    duration: '6 hours',
    topics: [
      'What are AI Tools?',
      'Function Calling — OpenAI & Anthropic',
      'Tool Schema Design (JSON Schema)',
      'Built-in Tools: Web Search, Code Interpreter, File I/O',
      'Custom Tool Creation',
      'MCP (Model Context Protocol) Deep Dive',
      'Building an MCP Server',
      'Tool Chaining & Composition',
      'Authentication & Secrets in Tools',
      'Tool Error Handling & Retries',
      'Integrating QA Tools: Jira, Slack, GitHub, TestRail',
      'Browser Automation Tools (Playwright as a Tool)',
      'Database Tools & SQL Execution',
      'Monitoring Tool Usage',
    ],
    labs: [
      'Build a Jira Bug-Filing Tool',
      'Create a Playwright Browser Tool',
      'Write an MCP Server from Scratch',
      'Tool Chain: Search → Summarise → File Bug',
      'Secure Secrets in Tool Execution',
    ],
    tools: ['MCP', 'OpenAI Tools', 'Anthropic Tools', 'Playwright', 'Jira API', 'GitHub API'],
    color: '#10b981',
    gradient: 'from-emerald-500 to-teal-700',
  },
  {
    id: 25,
    title: 'Agentic AI for Developers',
    subtitle: 'Code Generation, Review, Refactoring & PR Agents — Junior to Senior',
    icon: '💻',
    track: 'ai-builder',
    difficulty: 'Intermediate',
    duration: '7 hours',
    topics: [
      'Developer Roles in an AI-Augmented Team',
      'Code Generation Agents (GitHub Copilot, Cursor, Claude)',
      'Automated Code Review Agent',
      'Refactoring & Tech Debt Agent',
      'PR Description & Changelog Agent',
      'Dependency Audit Agent',
      'Unit Test Generator Agent',
      'Documentation Writer Agent',
      'Bug Fix Agent — Find Root Cause & Apply Fix',
      'IDE Integration: Cursor + Claude Rules',
      'Multi-Agent Code Pipeline (Plan → Code → Review → Test)',
      'Junior Dev Workflows vs Senior Dev Workflows',
    ],
    labs: [
      'Build a Code Review Agent from Scratch',
      'Auto-generate Unit Tests for any Function',
      'PR Description Generator Lab',
      'Refactoring Agent — Simplify Legacy Code',
      'Full Pipeline: Spec → Code → Tests → PR',
    ],
    tools: ['Claude API', 'GitHub API', 'Cursor', 'VS Code Extension API', 'Tree-sitter'],
    color: '#3b82f6',
    gradient: 'from-blue-500 to-indigo-700',
  },
  {
    id: 26,
    title: 'Agentic AI for DevOps',
    subtitle: 'CI/CD Agents, Incident Response, Infrastructure & Deployment Automation',
    icon: '🚀',
    track: 'ai-builder',
    difficulty: 'Advanced',
    duration: '7 hours',
    topics: [
      'DevOps Roles in an AI-Augmented Pipeline',
      'CI/CD Pipeline Agent — Analyse Build Failures',
      'Incident Response Agent — Alert to Postmortem',
      'Infrastructure-as-Code Agent (Terraform/Pulumi)',
      'Log Analysis & Anomaly Detection Agent',
      'Auto-Scaling Decision Agent',
      'Security Scan & CVE Triage Agent',
      'Deployment Approval Agent (Human-in-the-Loop)',
      'Cost Optimisation Agent (Cloud Billing)',
      'On-Call Runbook Agent',
      'Slack/PagerDuty Integration',
      'GitOps Agent — Auto PR for Config Changes',
    ],
    labs: [
      'Build a CI Failure Analysis Agent',
      'Incident Response Agent with Slack Alerts',
      'Terraform Plan Review Agent',
      'Log Anomaly Detector Lab',
      'Full On-Call Runbook Automation',
    ],
    tools: ['GitHub Actions API', 'PagerDuty', 'Slack API', 'Terraform', 'Datadog', 'AWS SDK'],
    color: '#f97316',
    gradient: 'from-orange-500 to-red-700',
  },
  {
    id: 27,
    title: 'Agentic AI for QA Engineers',
    subtitle: 'End-to-End QA Automation — Test Gen, Bug Triage, Regression & Release Agents',
    icon: '🧪',
    track: 'ai-builder',
    difficulty: 'Advanced',
    duration: '8 hours',
    topics: [
      'QA Roles in an AI-Augmented Team',
      'Test Case Generation Agent from Requirements',
      'Automated Bug Triage & Severity Classification',
      'Regression Test Selection Agent',
      'Visual Regression Agent (Screenshot Diffing)',
      'API Contract Validation Agent',
      'Test Data Generation Agent',
      'Flaky Test Detector & Fixer Agent',
      'Release Readiness Agent',
      'QA Reporting & Dashboard Agent',
      'End-to-End QA Pipeline Agent',
      'Full Bug Lifecycle Automation (Detect → File → Assign → Verify)',
    ],
    labs: [
      'Test Case Generator from Jira Stories',
      'Bug Triage Agent — Classify & Assign',
      'Regression Selector Agent',
      'Flaky Test Fixer Lab',
      'Full Release Readiness Automation',
    ],
    tools: ['Playwright', 'Jira API', 'GitHub API', 'Slack', 'Anthropic SDK', 'Applitools'],
    color: '#8b5cf6',
    gradient: 'from-violet-500 to-purple-800',
  },
];

export const trackColors: Record<string, string> = {
  core: 'bg-blue-500/20 text-blue-300 border-blue-500/30',
  automation: 'bg-green-500/20 text-green-300 border-green-500/30',
  'ai-quality': 'bg-purple-500/20 text-purple-300 border-purple-500/30',
  specialized: 'bg-orange-500/20 text-orange-300 border-orange-500/30',
  leadership: 'bg-yellow-500/20 text-yellow-300 border-yellow-500/30',
  'ai-builder': 'bg-indigo-500/20 text-indigo-300 border-indigo-500/30',
};

export const trackLabels: Record<string, string> = {
  core: 'Core Testing',
  automation: 'Automation',
  'ai-quality': 'AI Quality Engineering',
  specialized: 'Specialized',
  leadership: 'Leadership',
  'ai-builder': 'AI Builder',
};
